export type ToolCategory = 'Básicas' | 'Creativas' | 'Avanzadas';
export type ToolDomain = 'imagen' | 'pdf' | 'developer' | 'video' | 'audio';

export interface ToolMeta {
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  category: ToolCategory;
  domain: ToolDomain;
  icon: string;
  color: string;
  related: string[];
}

export const TOOLS: ToolMeta[] = [
  // ── IMAGEN · BÁSICAS ─────────────────────────────────────────
  {
    slug: 'comprimir',
    name: 'Comprimir imagen',
    description: 'Reduce el peso de tus imágenes sin perder calidad visible.',
    longDescription: 'Comprime imágenes JPG, PNG y WebP directamente en tu navegador. Visualiza la comparativa de tamaño antes y después con una barra de progreso en tiempo real.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Minimize2',
    color: 'blue',
    related: ['convertir', 'redimensionar', 'editor'],
  },
  {
    slug: 'redimensionar',
    name: 'Redimensionar imagen',
    description: 'Cambia el tamaño por píxeles exactos o porcentaje.',
    longDescription: 'Ajusta el ancho y alto de tu imagen con precisión. Mantén la proporción con un lock de aspect ratio o introduce dimensiones personalizadas.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Scaling',
    color: 'blue',
    related: ['recortar', 'comprimir', 'convertir'],
  },
  {
    slug: 'recortar',
    name: 'Recortar imagen',
    description: 'Selecciona y recorta el área exacta que necesitas.',
    longDescription: 'Usa el área arrastrable para seleccionar la zona de recorte. Elige entre presets populares como 1:1, 16:9, 4:3 o 9:16.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Crop',
    color: 'blue',
    related: ['redimensionar', 'girar', 'comprimir'],
  },
  {
    slug: 'convertir',
    name: 'Convertir formato',
    description: 'Convierte entre JPG, PNG, WebP y AVIF al instante.',
    longDescription: 'Cambia el formato de tu imagen con un clic. Soporte para JPG, PNG, WebP y AVIF. Ve el tamaño estimado del output antes de convertir.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'RefreshCw',
    color: 'blue',
    related: ['comprimir', 'redimensionar', 'editor'],
  },
  {
    slug: 'girar',
    name: 'Girar imagen',
    description: 'Rota y voltea tu imagen con preview en tiempo real.',
    longDescription: 'Gira tu imagen 90°, 180° o 270°. Voltéala horizontal o verticalmente. El preview se actualiza en tiempo real.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'RotateCw',
    color: 'blue',
    related: ['recortar', 'redimensionar', 'editor'],
  },
  {
    slug: 'redondear',
    name: 'Redondear esquinas',
    description: 'Añade esquinas redondeadas y exporta como PNG transparente.',
    longDescription: 'Aplica un radio de esquinas ajustable a tu imagen. El resultado se exporta como PNG con fondo transparente, ideal para avatares, logos y redes sociales.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Radius',
    color: 'blue',
    related: ['recorte-circular', 'marco', 'recortar'],
  },
  {
    slug: 'recorte-circular',
    name: 'Recorte circular',
    description: 'Recorta tu imagen en forma de círculo o elipse.',
    longDescription: 'Convierte cualquier imagen en un círculo o elipse perfecta. Exporta como PNG con fondo transparente. Ideal para fotos de perfil y avatares.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'CircleDashed',
    color: 'blue',
    related: ['redondear', 'recortar', 'marco'],
  },
  {
    slug: 'marco',
    name: 'Añadir marco',
    description: 'Rodea tu imagen con un marco de color y grosor ajustables.',
    longDescription: 'Añade un borde o marco a tu imagen eligiendo color, grosor y estilo. Perfecto para destacar fotos, crear capturas con bordes o preparar imágenes para publicaciones.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Frame',
    color: 'blue',
    related: ['redondear', 'sombra', 'editor'],
  },
  {
    slug: 'desenfoque',
    name: 'Desenfocar imagen',
    description: 'Aplica desenfoque gaussiano con intensidad ajustable.',
    longDescription: 'Desenfoca tu imagen con efecto gaussiano. Controla la intensidad del desenfoque para crear fondos borrosos, proteger información o aplicar efectos artísticos.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Aperture',
    color: 'blue',
    related: ['pixelar', 'editor', 'invertir'],
  },
  // ── IMAGEN · CREATIVAS ───────────────────────────────────────
  {
    slug: 'marca-de-agua',
    name: 'Marca de agua',
    description: 'Añade texto o imagen con opacidad y posición ajustables.',
    longDescription: 'Protege tus imágenes añadiendo una marca de agua de texto o imagen. Controla la opacidad, posición (9 puntos de anclaje) y tamaño.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Droplets',
    color: 'purple',
    related: ['meme', 'editor', 'comprimir'],
  },
  {
    slug: 'meme',
    name: 'Creador de memes',
    description: 'Crea memes con texto superior e inferior estilo clásico.',
    longDescription: 'Añade texto superior e inferior con fuente Impact y outline negro. Ajusta el tamaño y crea memes en segundos.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Laugh',
    color: 'purple',
    related: ['marca-de-agua', 'editor', 'comprimir'],
  },
  {
    slug: 'blancoynegro',
    name: 'Blanco y negro',
    description: 'Convierte tu imagen a escala de grises con ajuste de contraste.',
    longDescription: 'Transforma tus fotos a blanco y negro con control de brillo y contraste. Resultado profesional con la ponderación luminosa correcta (Rec. 709).',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Contrast',
    color: 'purple',
    related: ['invertir', 'editor', 'comprimir'],
  },
  {
    slug: 'invertir',
    name: 'Invertir colores',
    description: 'Aplica el efecto negativo invirtiendo todos los colores.',
    longDescription: 'Invierte los valores de color de tu imagen creando un efecto negativo. Útil para efectos artísticos, análisis de imágenes y creación de negativos fotográficos.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'SunMoon',
    color: 'purple',
    related: ['blancoynegro', 'editor', 'desenfoque'],
  },
  {
    slug: 'paleta',
    name: 'Extraer paleta de colores',
    description: 'Detecta los colores dominantes de cualquier imagen.',
    longDescription: 'Analiza tu imagen y extrae la paleta de colores dominantes. Obtén los códigos hexadecimales, cópialos al portapapeles y descarga la paleta como imagen.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Palette',
    color: 'purple',
    related: ['editor', 'blancoynegro', 'invertir'],
  },
  {
    slug: 'collage',
    name: 'Crear collage',
    description: 'Combina varias imágenes en una sola con diseños de cuadrícula.',
    longDescription: 'Sube entre 2 y 4 imágenes y combínalas en un collage con diferentes diseños de cuadrícula. Ajusta el espaciado y el color de fondo.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'LayoutGrid',
    color: 'purple',
    related: ['marco', 'redimensionar', 'comprimir'],
  },
  {
    slug: 'texto',
    name: 'Añadir texto',
    description: 'Escribe texto sobre tu imagen con fuente, color y posición.',
    longDescription: 'Añade texto personalizado a tu imagen con control sobre fuente, tamaño, color, contorno y posición. Perfecto para subtítulos, etiquetas y títulos.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Type',
    color: 'purple',
    related: ['marca-de-agua', 'meme', 'marco'],
  },
  // ── IMAGEN · AVANZADAS ───────────────────────────────────────
  {
    slug: 'editor',
    name: 'Editor de imagen',
    description: 'Ajusta brillo, contraste, saturación y aplica presets.',
    longDescription: 'Editor completo con controles de brillo, contraste, saturación, temperatura y nitidez. Incluye 6 presets: vintage, blanco y negro, vivid, fade, cinematic y cool.',
    category: 'Avanzadas',
    domain: 'imagen',
    icon: 'Sliders',
    color: 'orange',
    related: ['comprimir', 'convertir', 'girar'],
  },
  {
    slug: 'eliminar-fondo',
    name: 'Eliminar fondo (IA)',
    description: 'Elimina el fondo de tus fotos con inteligencia artificial.',
    longDescription: 'Usa IA para eliminar el fondo de forma automática. Descarga con fondo transparente (PNG) o elige un color de fondo sólido.',
    category: 'Avanzadas',
    domain: 'imagen',
    icon: 'Scissors',
    color: 'orange',
    related: ['editor', 'comprimir', 'convertir'],
  },
  {
    slug: 'html-a-imagen',
    name: 'HTML a imagen',
    description: 'Convierte código HTML y CSS en una imagen PNG o JPG.',
    longDescription: 'Escribe o pega código HTML con estilos CSS y captúralo como imagen. Ideal para crear OG images, banners o capturas de componentes.',
    category: 'Avanzadas',
    domain: 'imagen',
    icon: 'Code',
    color: 'orange',
    related: ['meme', 'marca-de-agua', 'editor'],
  },
  {
    slug: 'pixelar',
    name: 'Pixelar imagen',
    description: 'Censura zonas específicas o aplica efecto pixel art.',
    longDescription: 'Selecciona con el ratón la zona a pixelar y ajusta la intensidad con un slider. Perfecto para censurar caras, datos sensibles o crear efectos retro.',
    category: 'Avanzadas',
    domain: 'imagen',
    icon: 'Grid3x3',
    color: 'orange',
    related: ['recortar', 'editor', 'comprimir'],
  },
  {
    slug: 'sombra',
    name: 'Añadir sombra',
    description: 'Añade una sombra paralela a tu imagen con fondo transparente.',
    longDescription: 'Agrega una sombra de tipo drop shadow a tu imagen. Ajusta el desplazamiento, el desenfoque y el color. Exporta como PNG con fondo transparente.',
    category: 'Avanzadas',
    domain: 'imagen',
    icon: 'Layers',
    color: 'orange',
    related: ['marco', 'redondear', 'editor'],
  },

  // ── PDF · BÁSICAS ─────────────────────────────────────────────
  {
    slug: 'comprimir-pdf',
    name: 'Comprimir PDF',
    description: 'Reduce el tamaño de tu PDF conservando la calidad del texto.',
    longDescription: 'Comprime archivos PDF directamente en el navegador usando recodificación de objetos. Sin servidores, sin límites de tamaño. Ideal para adjuntar PDFs en emails o formularios con límite de peso.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FileDown',
    color: 'blue',
    related: ['unir-pdfs', 'dividir-pdf', 'pdf-a-jpg'],
  },
  {
    slug: 'unir-pdfs',
    name: 'Unir PDFs',
    description: 'Combina varios archivos PDF en uno solo conservando el orden.',
    longDescription: 'Fusiona múltiples PDFs en un único documento. Reordena los archivos arrastrando antes de unirlos. Sin límite de archivos y sin enviar nada al servidor.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Files',
    color: 'blue',
    related: ['dividir-pdf', 'comprimir-pdf', 'extraer-paginas-pdf'],
  },
  {
    slug: 'dividir-pdf',
    name: 'Dividir PDF',
    description: 'Divide un PDF en partes o extrae un rango de páginas.',
    longDescription: 'Divide un PDF en páginas individuales o extrae un rango específico como nuevo documento. Perfecto para separar informes, contratos o capítulos sin software adicional.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FileMinus2',
    color: 'blue',
    related: ['unir-pdfs', 'extraer-paginas-pdf', 'comprimir-pdf'],
  },
  {
    slug: 'pdf-a-jpg',
    name: 'PDF a JPG',
    description: 'Convierte cada página de tu PDF en una imagen JPG.',
    longDescription: 'Renderiza cada página de un PDF como imagen JPG de alta calidad directamente en el navegador con PDF.js. Descarga las imágenes individualmente o todas de una vez.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FileImage',
    color: 'blue',
    related: ['jpg-a-pdf', 'comprimir-pdf', 'dividir-pdf'],
  },
  {
    slug: 'jpg-a-pdf',
    name: 'JPG a PDF',
    description: 'Convierte una o varias imágenes en un documento PDF.',
    longDescription: 'Transforma imágenes JPG, PNG o WebP en un PDF listo para imprimir o compartir. Selecciona el tamaño de página (A4, Carta o automático) y ajusta la orientación.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FilePlus2',
    color: 'blue',
    related: ['pdf-a-jpg', 'unir-pdfs', 'comprimir-pdf'],
  },
  {
    slug: 'rotar-pdf',
    name: 'Rotar PDF',
    description: 'Gira las páginas de tu PDF 90°, 180° o 270°.',
    longDescription: 'Corrige la orientación de páginas escaneadas o rotadas en un PDF. Aplica la rotación a todas las páginas o elige páginas específicas. El resultado se descarga al instante.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'RotateCcw',
    color: 'blue',
    related: ['comprimir-pdf', 'dividir-pdf', 'extraer-paginas-pdf'],
  },
  {
    slug: 'extraer-paginas-pdf',
    name: 'Extraer páginas PDF',
    description: 'Selecciona y extrae páginas concretas de un PDF.',
    longDescription: 'Introduce el rango de páginas que quieres conservar (por ejemplo: 1-3, 5, 8-10) y genera un nuevo PDF con solo esas páginas. Sin instalación ni registro.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'BookOpen',
    color: 'blue',
    related: ['dividir-pdf', 'unir-pdfs', 'comprimir-pdf'],
  },
  // ── PDF · AVANZADAS ───────────────────────────────────────────
  {
    slug: 'extraer-texto-pdf',
    name: 'Extraer texto de PDF',
    description: 'Copia todo el texto de un PDF en segundos.',
    longDescription: 'Extrae el contenido textual de cualquier PDF directamente en el navegador usando PDF.js. Descarga el resultado como archivo .txt o cópialo al portapapeles.',
    category: 'Avanzadas',
    domain: 'pdf',
    icon: 'FileText',
    color: 'orange',
    related: ['dividir-pdf', 'extraer-paginas-pdf', 'proteger-pdf'],
  },
  {
    slug: 'proteger-pdf',
    name: 'Proteger PDF',
    description: 'Añade contraseña a un PDF para proteger su contenido.',
    longDescription: 'Cifra tu PDF con contraseña de usuario para que solo quien la conozca pueda abrirlo. Opcionalmente añade contraseña de propietario para restricciones de edición e impresión.',
    category: 'Avanzadas',
    domain: 'pdf',
    icon: 'Lock',
    color: 'orange',
    related: ['eliminar-password-pdf', 'comprimir-pdf', 'unir-pdfs'],
  },
  {
    slug: 'eliminar-password-pdf',
    name: 'Eliminar contraseña PDF',
    description: 'Desbloquea un PDF protegido con contraseña.',
    longDescription: 'Si conoces la contraseña de un PDF, puedes eliminarla y guardar el archivo desbloqueado. El proceso es 100% local: la contraseña nunca se envía a ningún servidor.',
    category: 'Avanzadas',
    domain: 'pdf',
    icon: 'Unlock',
    color: 'orange',
    related: ['proteger-pdf', 'comprimir-pdf', 'extraer-texto-pdf'],
  },

  // ── VIDEO · BÁSICAS ──────────────────────────────────────────
  {
    slug: 'comprimir-video',
    name: 'Comprimir vídeo',
    description: 'Reduce el tamaño de tu vídeo ajustando la calidad de compresión.',
    longDescription: 'Comprime tus vídeos MP4 y WebM directamente en el navegador con FFmpeg.wasm. Ajusta el nivel de calidad CRF para encontrar el equilibrio ideal entre tamaño y calidad visual.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Video',
    color: 'blue',
    related: ['convertir-video', 'recortar-video', 'extraer-audio'],
  },
  {
    slug: 'convertir-video',
    name: 'Convertir vídeo',
    description: 'Convierte entre MP4 y WebM sin perder calidad.',
    longDescription: 'Cambia el formato de tu vídeo entre MP4 (H.264) y WebM (VP8) sin instalar nada. El procesamiento es 100% local con FFmpeg.wasm.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Film',
    color: 'blue',
    related: ['comprimir-video', 'recortar-video', 'extraer-audio'],
  },
  {
    slug: 'extraer-audio',
    name: 'Extraer audio de vídeo',
    description: 'Extrae la pista de audio de cualquier vídeo como MP3 o WAV.',
    longDescription: 'Obtén solo el audio de un vídeo MP4 o WebM. Descarga el resultado como MP3 (comprimido) o WAV (sin pérdida). Procesamiento 100% local con FFmpeg.wasm.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Music',
    color: 'blue',
    related: ['convertir-video', 'comprimir-video', 'convertir-audio'],
  },
  {
    slug: 'video-a-gif',
    name: 'Vídeo a GIF',
    description: 'Convierte un fragmento de vídeo en un GIF animado.',
    longDescription: 'Transforma un clip de vídeo en un GIF animado ajustando el punto de inicio, la duración, los fotogramas por segundo y el ancho. Ideal para crear previews y contenido para redes sociales.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Clapperboard',
    color: 'blue',
    related: ['recortar-video', 'convertir-video', 'comprimir-video'],
  },
  {
    slug: 'recortar-video',
    name: 'Recortar vídeo',
    description: 'Recorta un vídeo seleccionando el punto de inicio y fin.',
    longDescription: 'Elimina partes del principio o el final de tu vídeo con precisión de segundos. Define el punto de entrada y salida y descarga el fragmento seleccionado. Sin pérdida de calidad cuando se usa copia directa.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Scissors',
    color: 'blue',
    related: ['comprimir-video', 'convertir-video', 'video-a-gif'],
  },

  // ── AUDIO · BÁSICAS ──────────────────────────────────────────
  {
    slug: 'comprimir-audio',
    name: 'Comprimir audio',
    description: 'Reduce el tamaño de archivos de audio ajustando el bitrate.',
    longDescription: 'Comprime archivos MP3, WAV y OGG reduciendo el bitrate. Elige entre varias calidades según tu necesidad: desde 64 kbps para voz hasta 320 kbps para música. Procesamiento 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Headphones',
    color: 'blue',
    related: ['convertir-audio', 'cortar-audio', 'extraer-audio'],
  },
  {
    slug: 'convertir-audio',
    name: 'Convertir audio',
    description: 'Convierte entre MP3, WAV, OGG y AAC sin pérdida innecesaria.',
    longDescription: 'Cambia el formato de tus archivos de audio entre MP3, WAV, OGG y AAC en el navegador con FFmpeg.wasm. Ideal para compatibilidad con distintos reproductores y plataformas.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Music2',
    color: 'blue',
    related: ['comprimir-audio', 'cortar-audio', 'extraer-audio'],
  },
  {
    slug: 'cortar-audio',
    name: 'Cortar audio',
    description: 'Recorta un fragmento de audio por tiempo de inicio y fin.',
    longDescription: 'Extrae un fragmento de cualquier archivo de audio definiendo el segundo de inicio y el segundo de fin. Útil para crear clips, tonos de llamada o extractos de canciones.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Radio',
    color: 'blue',
    related: ['comprimir-audio', 'unir-audios', 'convertir-audio'],
  },
  {
    slug: 'unir-audios',
    name: 'Unir audios',
    description: 'Combina varios archivos de audio en uno solo manteniendo el orden.',
    longDescription: 'Fusiona múltiples archivos de audio en un único archivo. Reordena las pistas antes de unirlas. El resultado se descarga como MP3. Sin enviar archivos al servidor.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'ListMusic',
    color: 'blue',
    related: ['cortar-audio', 'comprimir-audio', 'convertir-audio'],
  },
  {
    slug: 'cambiar-volumen',
    name: 'Cambiar volumen',
    description: 'Sube o baja el volumen de un audio con precisión en dB.',
    longDescription: 'Ajusta el volumen de cualquier archivo de audio entre -20 dB y +20 dB. También puedes normalizar el audio al nivel máximo sin distorsión. Procesamiento 100% local con FFmpeg.wasm.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Volume2',
    color: 'blue',
    related: ['comprimir-audio', 'cortar-audio', 'convertir-audio'],
  },

  // ── DEVELOPER · BÁSICAS ───────────────────────────────────────
  {
    slug: 'svg-a-png',
    name: 'SVG a PNG',
    description: 'Convierte SVG vectorial a PNG rasterizado con el tamaño que quieras.',
    longDescription: 'Renderiza cualquier SVG a PNG con dimensiones y fondo personalizados. Perfecto para exportar iconos, logos e ilustraciones vectoriales a formatos compatibles con cualquier plataforma.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'FileCode2',
    color: 'blue',
    related: ['imagen-a-base64', 'generar-favicon', 'eliminar-exif'],
  },
  {
    slug: 'colores-imagen',
    name: 'Colores de imagen',
    description: 'Extrae hex, RGB y HSL de los colores dominantes.',
    longDescription: 'Analiza tu imagen y obtén los colores dominantes con sus valores en hex, RGB y HSL listos para copiar. Ideal para documentar paletas de marca o extraer colores de referencias visuales.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Pipette',
    color: 'blue',
    related: ['eliminar-exif', 'imagen-a-base64', 'svg-a-png'],
  },
  {
    slug: 'eliminar-exif',
    name: 'Eliminar EXIF',
    description: 'Borra metadatos EXIF (GPS, cámara, fecha) de tus imágenes.',
    longDescription: 'Elimina todos los metadatos EXIF de tus fotos antes de publicarlas. Incluye GPS, modelo de cámara, fecha y hora. El proceso usa Canvas API y nunca sale de tu navegador.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'ShieldOff',
    color: 'blue',
    related: ['comprimir', 'colores-imagen', 'imagen-a-base64'],
  },
  {
    slug: 'imagen-a-base64',
    name: 'Imagen a Base64',
    description: 'Codifica cualquier imagen en Base64 para incrustarla en código.',
    longDescription: 'Convierte tu imagen a una cadena Base64 lista para usar en HTML, CSS, JSON o JavaScript. Elimina peticiones HTTP adicionales para imágenes pequeñas. Muestra ejemplos de uso en cada contexto.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Hash',
    color: 'blue',
    related: ['svg-a-png', 'generar-favicon', 'eliminar-exif'],
  },
  {
    slug: 'generar-favicon',
    name: 'Generar favicon',
    description: 'Genera todos los tamaños de favicon desde una imagen.',
    longDescription: 'Crea los tamaños estándar de favicon (16×16, 32×32, 48×48 y 180×180) desde cualquier imagen. Descarga cada PNG con el nombre correcto y copia las etiquetas HTML listas para tu `<head>`.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Bookmark',
    color: 'blue',
    related: ['svg-a-png', 'imagen-a-base64', 'recorte-circular'],
  },

  // ── IMAGEN · NUEVAS ─────────────────────────────────────────
  {
    slug: 'espejo',
    name: 'Voltear imagen',
    description: 'Refleja tu imagen horizontal o verticalmente con un clic.',
    longDescription: 'Voltea cualquier imagen en espejo de forma horizontal, vertical o en ambos ejes. Preview instantáneo y descarga en el mismo formato que el original.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'FlipHorizontal2',
    color: 'blue',
    related: ['girar', 'recortar', 'editor'],
  },
  {
    slug: 'foto-carnet',
    name: 'Foto carnet',
    description: 'Crea fotos de carnet y pasaporte con los tamaños oficiales.',
    longDescription: 'Genera fotos de carnet para DNI, pasaporte, visado, carnet de conducir y más. Selecciona el formato estándar y recorta automáticamente tu foto al tamaño oficial.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'IdCard',
    color: 'blue',
    related: ['recortar', 'redimensionar', 'recorte-circular'],
  },
  {
    slug: 'redimensionar-redes',
    name: 'Redimensionar para redes',
    description: 'Ajusta tus imágenes a los tamaños perfectos para Instagram, YouTube y más.',
    longDescription: 'Redimensiona tus imágenes a las medidas exactas de Instagram, Twitter/X, YouTube, Facebook, TikTok, LinkedIn y WhatsApp con un solo clic. Elige entre recortar o rellenar con fondo.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'MonitorSmartphone',
    color: 'blue',
    related: ['redimensionar', 'recortar', 'thumbnail-youtube'],
  },
  {
    slug: 'efecto-vintage',
    name: 'Efecto vintage',
    description: 'Aplica efectos retro y vintage a tus fotos: sepia, cine, polaroid y más.',
    longDescription: 'Transforma tus fotos con efectos vintage profesionales. Elige entre Sepia, Vintage (faded + viñeta), Cine (grano + alto contraste), Polaroid y Noir. Controla la intensidad con un slider.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Sparkles',
    color: 'purple',
    related: ['blancoynegro', 'editor', 'invertir'],
  },
  {
    slug: 'thumbnail-youtube',
    name: 'Miniatura YouTube',
    description: 'Crea miniaturas de YouTube de 1280×720 con texto y fondo personalizado.',
    longDescription: 'Diseña miniaturas profesionales para YouTube en el tamaño perfecto (1280×720 px). Sube una imagen de fondo, añade título con fuente y color personalizables, y descarga en PNG.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'PlaySquare',
    color: 'purple',
    related: ['redimensionar-redes', 'texto', 'editor'],
  },
  {
    slug: 'imagenes-a-gif',
    name: 'Imágenes a GIF',
    description: 'Convierte varias imágenes en un GIF animado con velocidad ajustable.',
    longDescription: 'Crea GIFs animados desde múltiples imágenes JPG o PNG. Sube hasta 20 fotogramas, ajusta la velocidad de cada frame y el ancho del GIF. Optimización de paleta con FFmpeg.wasm.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'ImagePlay',
    color: 'purple',
    related: ['video-a-gif', 'collage', 'comprimir'],
  },

  // ── PDF · NUEVAS ─────────────────────────────────────────────
  {
    slug: 'marca-agua-pdf',
    name: 'Marca de agua en PDF',
    description: 'Añade texto en marca de agua a todas las páginas de un PDF.',
    longDescription: 'Protege tus documentos PDF añadiendo un texto en marca de agua diagonal. Controla el texto, tamaño, opacidad y color. Se aplica a todas las páginas. Sin subir archivos al servidor.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Stamp',
    color: 'blue',
    related: ['proteger-pdf', 'numerar-paginas-pdf', 'firmar-pdf'],
  },
  {
    slug: 'numerar-paginas-pdf',
    name: 'Numerar páginas PDF',
    description: 'Añade numeración automática a todas las páginas de tu PDF.',
    longDescription: 'Numera las páginas de tu PDF automáticamente. Elige la posición (inferior centro, inferior derecho, superior derecho), el número inicial y el formato (1, Página 1/N). Sin instalar nada.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'ListOrdered',
    color: 'blue',
    related: ['marca-agua-pdf', 'rotar-pdf', 'comprimir-pdf'],
  },
  {
    slug: 'firmar-pdf',
    name: 'Firmar PDF',
    description: 'Dibuja tu firma y colócala en cualquier página del PDF.',
    longDescription: 'Crea tu firma digital dibujándola con el ratón o el dedo, y colócala en la página que quieras del PDF. Elige el tamaño y la posición exacta. Procesamiento 100% local.',
    category: 'Avanzadas',
    domain: 'pdf',
    icon: 'PenLine',
    color: 'orange',
    related: ['proteger-pdf', 'marca-agua-pdf', 'unir-pdfs'],
  },
  {
    slug: 'pdf-a-png',
    name: 'PDF a PNG',
    description: 'Convierte cada página de tu PDF en una imagen PNG sin pérdida.',
    longDescription: 'Renderiza cada página de un PDF como imagen PNG de alta calidad. PNG es ideal para PDFs con texto, gráficos vectoriales o cuando necesitas fondo transparente.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'ScanLine',
    color: 'blue',
    related: ['pdf-a-jpg', 'dividir-pdf', 'comprimir-pdf'],
  },
  {
    slug: 'reordenar-paginas-pdf',
    name: 'Reordenar páginas PDF',
    description: 'Cambia el orden de las páginas de tu PDF arrastrando o con botones.',
    longDescription: 'Reorganiza las páginas de cualquier PDF de forma visual. Mueve las páginas hacia arriba o hacia abajo con botones intuitivos y descarga el PDF con el nuevo orden.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'ArrowUpDown',
    color: 'blue',
    related: ['dividir-pdf', 'unir-pdfs', 'extraer-paginas-pdf'],
  },
  {
    slug: 'recortar-pdf',
    name: 'Recortar márgenes PDF',
    description: 'Elimina los márgenes en blanco de un PDF ajustando el área visible.',
    longDescription: 'Recorta los márgenes de todas las páginas de un PDF definiendo el margen en milímetros para cada lado. Ideal para eliminar espacios en blanco excesivos de documentos escaneados.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Maximize2',
    color: 'blue',
    related: ['comprimir-pdf', 'rotar-pdf', 'extraer-paginas-pdf'],
  },

  // ── DEVELOPER · NUEVAS ───────────────────────────────────────
  {
    slug: 'generar-qr',
    name: 'Generador de QR',
    description: 'Crea códigos QR para URLs, texto o contactos en segundos.',
    longDescription: 'Genera códigos QR personalizados para cualquier URL, texto o dato. Ajusta el tamaño, los colores y el nivel de corrección de errores. Descarga en PNG sin registro.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'QrCode',
    color: 'blue',
    related: ['imagen-a-base64', 'generar-favicon', 'svg-a-png'],
  },
  {
    slug: 'formatear-json',
    name: 'Formatear JSON',
    description: 'Formatea, valida y minifica JSON con un clic.',
    longDescription: 'Pega tu JSON y fórmatealo con 2 o 4 espacios, minifícalo o valídalo al instante. Muestra errores con el número de línea. Copia el resultado o descárgalo como .json.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Braces',
    color: 'blue',
    related: ['codificar-url', 'imagen-a-base64', 'convertir-color'],
  },
  {
    slug: 'codificar-url',
    name: 'Codificar URL',
    description: 'Codifica y decodifica URLs y componentes de URL al instante.',
    longDescription: 'Codifica y decodifica URLs usando encodeURI / decodeURI y encodeURIComponent / decodeURIComponent. Resultado en tiempo real al escribir. Copia con un clic.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Link2',
    color: 'blue',
    related: ['formatear-json', 'imagen-a-base64', 'convertir-color'],
  },
  {
    slug: 'convertir-color',
    name: 'Convertir colores',
    description: 'Convierte colores entre HEX, RGB, HSL y HSB al instante.',
    longDescription: 'Introduce un color en cualquier formato (HEX, RGB, HSL, HSB) y obtén automáticamente sus equivalentes en todos los demás. Previsualiza el color y copia cada valor con un clic.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Paintbrush2',
    color: 'blue',
    related: ['colores-imagen', 'paleta', 'codificar-url'],
  },

  // ── VIDEO · NUEVAS ───────────────────────────────────────────
  {
    slug: 'cambiar-velocidad',
    name: 'Cambiar velocidad de vídeo',
    description: 'Acelera o ralentiza tu vídeo manteniendo la calidad de audio.',
    longDescription: 'Cambia la velocidad de reproducción de cualquier vídeo: desde 0.25x en cámara lenta hasta 2x en acelerado. El audio se ajusta automáticamente con corrección de tono. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Gauge',
    color: 'blue',
    related: ['comprimir-video', 'recortar-video', 'convertir-video'],
  },
  {
    slug: 'anadir-audio-video',
    name: 'Añadir audio a vídeo',
    description: 'Reemplaza o mezcla el audio de un vídeo con otro archivo de audio.',
    longDescription: 'Combina un vídeo con un archivo de audio. Elige entre reemplazar el audio existente o mezclarlo como música de fondo. El vídeo no se re-codifica, manteniendo la calidad original.',
    category: 'Básicas',
    domain: 'video',
    icon: 'AudioLines',
    color: 'blue',
    related: ['extraer-audio', 'convertir-video', 'comprimir-video'],
  },

  // ── AUDIO · NUEVAS ───────────────────────────────────────────
  {
    slug: 'velocidad-audio',
    name: 'Cambiar velocidad de audio',
    description: 'Acelera o ralentiza el audio conservando el tono original.',
    longDescription: 'Ajusta la velocidad de reproducción de cualquier audio entre 0.5x y 2x sin cambiar el tono (pitch preservation). Perfecto para podcasts, audiolibros o prácticas musicales.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'FastForward',
    color: 'blue',
    related: ['cortar-audio', 'cambiar-volumen', 'convertir-audio'],
  },
  {
    slug: 'revertir-audio',
    name: 'Revertir audio',
    description: 'Reproduce tu audio al revés con el efecto reverse.',
    longDescription: 'Invierte un archivo de audio para reproducirlo de atrás hacia adelante. Perfecto para efectos creativos, música experimental y producción de audio. Procesamiento 100% local con FFmpeg.wasm.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Rewind',
    color: 'blue',
    related: ['cortar-audio', 'convertir-audio', 'comprimir-audio'],
  },

  // ── VÍDEO · NUEVAS 2 ─────────────────────────────────────────
  {
    slug: 'rotar-video',
    name: 'Rotar vídeo',
    description: 'Gira tu vídeo 90°, 180° o 270° con un clic.',
    longDescription: 'Rota cualquier vídeo grabado en orientación incorrecta. Elige entre 90° a la derecha, 90° a la izquierda o 180°. El audio se preserva. Procesamiento 100% local con FFmpeg.wasm.',
    category: 'Básicas',
    domain: 'video',
    icon: 'RotateCw',
    color: 'blue',
    related: ['comprimir-video', 'recortar-video', 'convertir-video'],
  },
  {
    slug: 'unir-videos',
    name: 'Unir vídeos',
    description: 'Combina varios vídeos en uno solo manteniendo el orden.',
    longDescription: 'Fusiona múltiples vídeos en un único archivo MP4. Sube hasta 10 clips, reordénalos y descarga el resultado. Re-codificación con libx264 para máxima compatibilidad.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Merge',
    color: 'blue',
    related: ['recortar-video', 'comprimir-video', 'convertir-video'],
  },
  {
    slug: 'silenciar-video',
    name: 'Silenciar vídeo',
    description: 'Elimina el audio de un vídeo con un solo clic.',
    longDescription: 'Elimina completamente la pista de audio de cualquier vídeo. El stream de vídeo se copia sin re-codificar para preservar la calidad original. Perfecto para vídeos de fondo o presentaciones.',
    category: 'Básicas',
    domain: 'video',
    icon: 'VolumeX',
    color: 'blue',
    related: ['anadir-audio-video', 'comprimir-video', 'recortar-video'],
  },
  {
    slug: 'capturar-fotograma',
    name: 'Capturar fotograma',
    description: 'Extrae cualquier fotograma de un vídeo como imagen PNG.',
    longDescription: 'Selecciona el segundo exacto de tu vídeo y extrae ese fotograma como imagen PNG de alta calidad. Ideal para crear miniaturas, capturas de pantalla o extraer imágenes de grabaciones.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Camera',
    color: 'blue',
    related: ['video-a-gif', 'recortar-video', 'comprimir-video'],
  },

  // ── DEVELOPER · NUEVAS 2 ─────────────────────────────────────
  {
    slug: 'base64-texto',
    name: 'Base64 texto',
    description: 'Codifica y decodifica texto en Base64 al instante.',
    longDescription: 'Convierte cualquier texto a Base64 y viceversa de forma instantánea. Soporta Unicode, emojis y caracteres especiales. Útil para tokens de API, configuraciones, credenciales y datos en JSON.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Binary',
    color: 'blue',
    related: ['imagen-a-base64', 'codificar-url', 'formatear-json'],
  },
  {
    slug: 'minificador-css',
    name: 'Minificador CSS',
    description: 'Minifica y comprime tu CSS eliminando espacios y comentarios.',
    longDescription: 'Reduce el tamaño de tus archivos CSS eliminando espacios en blanco, saltos de línea y comentarios. También incluye un modo de formateo para hacer legible un CSS minificado. Sin dependencias externas.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Code2',
    color: 'blue',
    related: ['formatear-json', 'codificar-url', 'convertir-color'],
  },
  {
    slug: 'csv-a-json',
    name: 'CSV a JSON',
    description: 'Convierte archivos CSV a JSON y viceversa en segundos.',
    longDescription: 'Transforma datos CSV a formato JSON estructurado usando la primera fila como cabecera. También convierte JSON a CSV. Perfecto para importar/exportar datos entre herramientas y APIs.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Table',
    color: 'blue',
    related: ['formatear-json', 'codificar-url', 'base64-texto'],
  },
  {
    slug: 'calcular-hash',
    name: 'Calcular hash',
    description: 'Genera hashes SHA-256, SHA-1 y SHA-512 de texto o archivos.',
    longDescription: 'Calcula el hash criptográfico de texto o archivos usando SHA-1, SHA-256, SHA-384 y SHA-512 con la Web Crypto API nativa del navegador. Útil para verificar integridad de archivos y seguridad.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'ShieldCheck',
    color: 'blue',
    related: ['base64-texto', 'imagen-a-base64', 'codificar-url'],
  },

  // ── IMAGEN · NUEVAS 3 ─────────────────────────────────────────
  {
    slug: 'ajustar-hsb',
    name: 'Ajustar color',
    description: 'Ajusta el tono, saturación, brillo y contraste con sliders en tiempo real.',
    longDescription: 'Modifica el tono (hue), la saturación, el brillo y el contraste de tu imagen con sliders precisos. Preview en tiempo real y exportación en JPG. Ideal para corrección de color sin software.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'SlidersHorizontal',
    color: 'purple',
    related: ['editor', 'blancoynegro', 'efecto-vintage'],
  },
  {
    slug: 'efecto-boceto',
    name: 'Efecto boceto',
    description: 'Convierte cualquier foto en un dibujo a lápiz con efecto pencil sketch.',
    longDescription: 'Transforma tus fotografías en bocetos artísticos a lápiz usando la técnica color dodge. Controla la suavidad del trazo con un slider. El resultado es una imagen en escala de grises con aspecto de dibujo manual.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Pencil',
    color: 'purple',
    related: ['blancoynegro', 'efecto-vintage', 'editor'],
  },
  {
    slug: 'cambiar-fondo',
    name: 'Cambiar fondo',
    description: 'Reemplaza el fondo de tu imagen por cualquier color sólido.',
    longDescription: 'Añade o cambia el color de fondo de cualquier imagen. Especialmente útil para PNGs con transparencia: rellena el fondo con blanco, negro o cualquier color personalizado. Ideal para e-commerce y redes sociales.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'PaintBucket',
    color: 'blue',
    related: ['eliminar-fondo', 'recorte-circular', 'marco'],
  },
  {
    slug: 'mosaico',
    name: 'Mosaico de imagen',
    description: 'Repite tu imagen en una cuadrícula de N×M tiles.',
    longDescription: 'Crea un mosaico repitiendo tu imagen en una cuadrícula configurable de hasta 6 columnas × 6 filas. Perfecto para fondos de pantalla, papeles de pared, packaging y efectos de diseño gráfico.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Grid2x2',
    color: 'purple',
    related: ['collage', 'redimensionar', 'marco'],
  },
  {
    slug: 'efecto-duotono',
    name: 'Efecto duotono',
    description: 'Aplica un efecto duotono de dos colores a tus imágenes.',
    longDescription: 'Crea efectos duotono profesionales mapeando las sombras y las luces de tu imagen a dos colores personalizados. Incluye 5 combinaciones preset populares y soporte para cualquier color.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Layers2',
    color: 'purple',
    related: ['blancoynegro', 'editor', 'efecto-vintage'],
  },

  // ── PDF · NUEVAS 3 ────────────────────────────────────────────
  {
    slug: 'eliminar-paginas-pdf',
    name: 'Eliminar páginas PDF',
    description: 'Borra páginas específicas de un PDF por número o rango.',
    longDescription: 'Elimina páginas individuales o rangos de páginas de cualquier PDF. Indica qué páginas borrar (ej: 1, 3, 5-7) y descarga el PDF resultante sin esas páginas. Sin límite de tamaño, 100% local.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FileX',
    color: 'blue',
    related: ['extraer-paginas-pdf', 'dividir-pdf', 'reordenar-paginas-pdf'],
  },
  {
    slug: 'anadir-imagen-pdf',
    name: 'Añadir imagen a PDF',
    description: 'Inserta una imagen JPG o PNG en una página de tu PDF.',
    longDescription: 'Añade imágenes (JPG o PNG) en cualquier página de tu PDF con control de posición X/Y y tamaño. Perfecto para insertar firmas escaneadas, sellos, logos o cualquier imagen en un documento.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'ImagePlus',
    color: 'blue',
    related: ['firmar-pdf', 'anadir-texto-pdf', 'marca-agua-pdf'],
  },
  {
    slug: 'pdf-en-blanco',
    name: 'Crear PDF en blanco',
    description: 'Genera un PDF en blanco con el tamaño y número de páginas que necesites.',
    longDescription: 'Crea PDFs en blanco con tamaños estándar (A4, A3, A5, Carta, Legal) en orientación vertical u horizontal. Elige cuántas páginas necesitas (hasta 100). Ideal para plantillas, formularios y documentos base.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FilePlus',
    color: 'blue',
    related: ['unir-pdfs', 'anadir-texto-pdf', 'anadir-imagen-pdf'],
  },

  // ── VÍDEO · NUEVAS 3 ─────────────────────────────────────────
  {
    slug: 'voltear-video',
    name: 'Voltear vídeo',
    description: 'Voltea tu vídeo en espejo horizontal, vertical o en ambos ejes.',
    longDescription: 'Refleja cualquier vídeo horizontal o verticalmente con FFmpeg.wasm. Útil para corregir vídeos de cámara frontal, crear efectos de espejo o cumplir requisitos de plataformas. El audio se preserva.',
    category: 'Básicas',
    domain: 'video',
    icon: 'FlipHorizontal',
    color: 'blue',
    related: ['rotar-video', 'comprimir-video', 'recortar-video'],
  },
  {
    slug: 'recortar-area-video',
    name: 'Recortar área de vídeo',
    description: 'Recorta un área específica del vídeo definiendo ancho, alto y posición.',
    longDescription: 'Extrae un área rectangular de cualquier vídeo especificando el ancho, alto y las coordenadas de inicio en píxeles. Ideal para eliminar barras negras, recortar bordes o extraer una región de interés. El audio se preserva.',
    category: 'Básicas',
    domain: 'video',
    icon: 'ScanSearch',
    color: 'blue',
    related: ['recortar-video', 'cambiar-resolucion-video', 'comprimir-video'],
  },
  {
    slug: 'cambiar-resolucion-video',
    name: 'Cambiar resolución de vídeo',
    description: 'Escala tu vídeo a 4K, 1080p, 720p, 480p o una resolución personalizada.',
    longDescription: 'Cambia la resolución de cualquier vídeo con presets populares o dimensiones personalizadas. La herramienta mantiene la relación de aspecto original y añade padding si es necesario. El audio se preserva.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Monitor',
    color: 'blue',
    related: ['comprimir-video', 'convertir-video', 'recortar-area-video'],
  },
  {
    slug: 'marca-agua-video',
    name: 'Marca de agua en vídeo',
    description: 'Añade texto como marca de agua a tu vídeo con posición y opacidad ajustables.',
    longDescription: 'Incrusta texto permanente como marca de agua en tu vídeo usando FFmpeg drawtext. Elige la posición (centro, esquinas), el tamaño de fuente y la opacidad. El texto queda grabado en el stream de vídeo.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Stamp',
    color: 'blue',
    related: ['silenciar-video', 'comprimir-video', 'recortar-video'],
  },

  // ── AUDIO · NUEVAS 2 ─────────────────────────────────────────
  {
    slug: 'agregar-fade-audio',
    name: 'Agregar fade a audio',
    description: 'Añade fade in y fade out suaves a cualquier archivo de audio.',
    longDescription: 'Aplica efectos de entrada y salida gradual a tu audio. Configura la duración del fade in (inicio desde silencio) y fade out (fin en silencio) de forma independiente. Compatible con todos los formatos de audio.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'TrendingUp',
    color: 'blue',
    related: ['cortar-audio', 'cambiar-volumen', 'mezclar-audios'],
  },
  {
    slug: 'mezclar-audios',
    name: 'Mezclar audios',
    description: 'Combina dos pistas de audio en una sola con control de volumen independiente.',
    longDescription: 'Superpone dos archivos de audio en una sola pista. Controla el volumen de cada pista de forma independiente. Perfecto para añadir música de fondo a una locución, crear karaoke o superponer efectos de sonido.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Combine',
    color: 'blue',
    related: ['unir-audios', 'cambiar-volumen', 'agregar-fade-audio'],
  },
  {
    slug: 'cambiar-tono',
    name: 'Cambiar tono de audio',
    description: 'Sube o baja el tono musical de un audio en semitonos sin cambiar la velocidad.',
    longDescription: 'Ajusta el tono de cualquier audio entre -12 y +12 semitonos (una octava completa) sin modificar la velocidad de reproducción. Ideal para transportar música, crear efectos de voz o adaptar canciones para cantar.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Music4',
    color: 'blue',
    related: ['velocidad-audio', 'convertir-audio', 'comprimir-audio'],
  },

  // ── DEVELOPER · NUEVAS 3 ─────────────────────────────────────
  {
    slug: 'regex-tester',
    name: 'Tester de Regex',
    description: 'Prueba expresiones regulares JavaScript con resaltado de coincidencias en tiempo real.',
    longDescription: 'Escribe una expresión regular y pruébala contra cualquier texto. Las coincidencias se resaltan en tiempo real, con detalle de índices y grupos de captura. Soporta todos los flags de JavaScript (g, i, m, s).',
    category: 'Básicas',
    domain: 'developer',
    icon: 'TestTube2',
    color: 'blue',
    related: ['formatear-json', 'contador-palabras', 'codificar-url'],
  },
  {
    slug: 'generador-uuid',
    name: 'Generador de UUID',
    description: 'Genera UUIDs v4 criptográficamente seguros al instante.',
    longDescription: 'Genera uno o hasta 100 UUID versión 4 usando la Web Crypto API. Opciones para formato con/sin guiones y en mayúsculas o minúsculas. Copia cada UUID o todos de una vez al portapapeles.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Fingerprint',
    color: 'blue',
    related: ['calcular-hash', 'base64-texto', 'codificar-url'],
  },
  {
    slug: 'contador-palabras',
    name: 'Contador de palabras',
    description: 'Cuenta palabras, caracteres, frases, párrafos y tiempo de lectura al instante.',
    longDescription: 'Analiza cualquier texto y muestra en tiempo real el número de palabras, caracteres (con y sin espacios), frases, párrafos, líneas y tiempo estimado de lectura. Útil para artículos, SEO, tweets y documentos académicos.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'AlignLeft',
    color: 'blue',
    related: ['regex-tester', 'formatear-json', 'minificador-html'],
  },
  {
    slug: 'convertir-timestamp',
    name: 'Convertir timestamp',
    description: 'Convierte entre Unix timestamp y fecha legible en ambas direcciones.',
    longDescription: 'Transforma Unix timestamps (segundos o milisegundos) a fechas legibles en formato local, UTC e ISO 8601, y viceversa. Detecta automáticamente si el timestamp está en segundos o milisegundos. Copia cualquier resultado.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Clock',
    color: 'blue',
    related: ['formatear-json', 'generador-uuid', 'codificar-url'],
  },
  {
    slug: 'minificador-html',
    name: 'Minificador HTML',
    description: 'Minifica y formatea HTML eliminando espacios y comentarios innecesarios.',
    longDescription: 'Reduce el tamaño de archivos HTML eliminando comentarios, espacios en blanco redundantes y saltos de línea. También incluye modo de formateo para hacer legible un HTML comprimido. Sin dependencias externas.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'FileCode',
    color: 'blue',
    related: ['minificador-css', 'formatear-json', 'contador-palabras'],
  },

  // ── IMAGEN · NUEVAS 2 ─────────────────────────────────────────
  {
    slug: 'imagen-a-webp',
    name: 'Convertir a WebP',
    description: 'Convierte imágenes JPG y PNG a formato WebP con calidad ajustable.',
    longDescription: 'Transforma tus imágenes JPG o PNG al formato WebP de Google, que ofrece hasta un 30% menos de tamaño con la misma calidad visual. Elige la calidad y descarga al instante. 100% en el navegador.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'ImageUp',
    color: 'blue',
    related: ['comprimir', 'convertir', 'redimensionar'],
  },

  // ── PDF · NUEVAS 2 ────────────────────────────────────────────
  {
    slug: 'anadir-texto-pdf',
    name: 'Añadir texto a PDF',
    description: 'Inserta texto personalizado en cualquier posición de tu PDF.',
    longDescription: 'Añade anotaciones de texto a cualquier página de un PDF. Personaliza la posición (X/Y en porcentaje), el tamaño de fuente y el color. Perfecto para completar formularios o añadir notas. 100% local.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Type',
    color: 'blue',
    related: ['firmar-pdf', 'marca-agua-pdf', 'numerar-paginas-pdf'],
  },

  // ── DEVELOPER · NUEVAS ───────────────────────────────────────
  {
    slug: 'generador-contrasenas',
    name: 'Generador de contraseñas',
    description: 'Genera contraseñas seguras y aleatorias con opciones avanzadas.',
    longDescription: 'Crea contraseñas criptográficamente seguras usando la Web Crypto API. Controla la longitud (6-64 caracteres), los tipos de caracteres y genera hasta 20 contraseñas a la vez. Indicador de fortaleza incluido.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'KeyRound',
    color: 'blue',
    related: ['calcular-hash', 'generador-uuid', 'base64-texto'],
  },
  {
    slug: 'lorem-ipsum',
    name: 'Lorem ipsum',
    description: 'Genera párrafos, frases o palabras de texto Lorem Ipsum.',
    longDescription: 'Genera texto de relleno Lorem ipsum en tres modos: párrafos, frases o palabras sueltas. Ajusta la cantidad con un slider, activa o desactiva el inicio clásico «Lorem ipsum…», y descarga el resultado como .txt.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'AlignJustify',
    color: 'blue',
    related: ['contador-palabras', 'minificador-html', 'formatear-json'],
  },
  {
    slug: 'gradiente-css',
    name: 'Generador de gradientes CSS',
    description: 'Crea gradientes CSS lineales y radiales con preview en tiempo real.',
    longDescription: 'Diseña gradientes CSS con hasta 5 colores, control de ángulo y posición de cada stop. Elige entre gradiente lineal o radial. Preview en tiempo real y copia el código CSS listo para usar. Incluye 5 presets.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Layers',
    color: 'blue',
    related: ['convertir-color', 'colores-imagen', 'minificador-css'],
  },
  {
    slug: 'minificador-js',
    name: 'Minificador JavaScript',
    description: 'Minifica y formatea código JavaScript eliminando comentarios y espacios.',
    longDescription: 'Reduce el tamaño de archivos JavaScript eliminando comentarios de bloque y de línea, y colapsando espacios en blanco. También incluye modo de formateo para hacer legible un JS minificado. Muestra el porcentaje de reducción.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Zap',
    color: 'blue',
    related: ['minificador-css', 'minificador-html', 'formatear-json'],
  },

  // ── AUDIO · NUEVAS ───────────────────────────────────────────
  {
    slug: 'anadir-silencio',
    name: 'Añadir silencio a audio',
    description: 'Añade segundos de silencio al inicio y/o al final de cualquier audio.',
    longDescription: 'Agrega silencio al comienzo o al final de un archivo de audio con precisión de 0.5 segundos. Útil para dar margen antes de que empiece una pista, sincronizar audios o cumplir requisitos de duración. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Volume',
    color: 'blue',
    related: ['cortar-audio', 'unir-audios', 'agregar-fade-audio'],
  },
  {
    slug: 'convertir-a-mono',
    name: 'Convertir estéreo a mono',
    description: 'Mezcla los canales estéreo en uno solo para reducir el tamaño del audio.',
    longDescription: 'Convierte cualquier audio estéreo a mono mezclando los canales izquierdo y derecho. El resultado ocupa aproximadamente la mitad de espacio. Ideal para podcasts, voz en off y archivos donde el tamaño importa. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Headphones',
    color: 'blue',
    related: ['comprimir-audio', 'convertir-audio', 'cambiar-volumen'],
  },

  // ── IMAGEN · NUEVAS ──────────────────────────────────────────
  {
    slug: 'comprimir-objetivo',
    name: 'Comprimir a tamaño objetivo',
    description: 'Comprime tu imagen hasta alcanzar un tamaño de archivo específico en KB.',
    longDescription: 'Introduce el peso máximo deseado (en KB) y la herramienta busca automáticamente el nivel de calidad JPEG que produce el archivo más grande posible sin superar ese límite. Búsqueda binaria con hasta 15 iteraciones. 100% en el navegador.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Target',
    color: 'blue',
    related: ['comprimir', 'redimensionar', 'convertir'],
  },
  {
    slug: 'fondo-degradado',
    name: 'Fondo degradado',
    description: 'Añade un fondo con degradado de color a tu imagen o PNG transparente.',
    longDescription: 'Aplica un fondo de gradiente lineal o radial a cualquier imagen. Especialmente útil para PNGs con transparencia: logos, ilustraciones o imágenes con fondo eliminado. Elige entre 5 presets o personaliza los colores. Exporta como PNG.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Sunset',
    color: 'purple',
    related: ['cambiar-fondo', 'eliminar-fondo', 'marco'],
  },

  // ── NUEVAS 20 HERRAMIENTAS ────────────────────────────────────

  // Imagen
  {
    slug: 'nitidez',
    name: 'Aumentar nitidez',
    description: 'Enfoca y aumenta la nitidez de tus imágenes con unsharp mask.',
    longDescription: 'Aplica el algoritmo unsharp mask para realzar los bordes y detalles de tu imagen. Controla la intensidad del enfoque con un slider. Ideal para fotos borrosas o imágenes que necesitan más definición.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Focus',
    color: 'blue',
    related: ['desenfoque', 'editor', 'ajustar-hsb'],
  },
  {
    slug: 'ajustar-niveles',
    name: 'Ajustar niveles',
    description: 'Corrige la exposición ajustando los puntos negro, blanco y gamma.',
    longDescription: 'Controla los niveles de entrada y salida de tu imagen con precisión: punto negro, punto blanco y corrección gamma. Ideal para corregir imágenes subexpuestas o sobreexpuestas sin software profesional.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'BarChart2',
    color: 'blue',
    related: ['editor', 'ajustar-hsb', 'blancoynegro'],
  },
  {
    slug: 'efecto-oleo',
    name: 'Efecto óleo',
    description: 'Transforma tu foto en una pintura al óleo artística.',
    longDescription: 'Aplica el efecto de pintura al óleo sobre cualquier imagen. El algoritmo analiza vecindades de píxeles para crear trazos pictóricos. Controla el radio del pincel para diferentes estilos artísticos.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Brush',
    color: 'purple',
    related: ['efecto-vintage', 'efecto-boceto', 'editor'],
  },
  {
    slug: 'desvanecer-bordes',
    name: 'Desvanecer bordes',
    description: 'Aplica un fade suave en los bordes de la imagen con fondo transparente.',
    longDescription: 'Crea un efecto de desvanecimiento en los bordes de tu imagen. Los extremos se vuelven gradualmente transparentes, ideal para composiciones, presentaciones y overlays. Exporta como PNG con transparencia.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Blend',
    color: 'purple',
    related: ['sombra', 'marco', 'recorte-circular'],
  },

  // PDF
  {
    slug: 'intercalar-pdfs',
    name: 'Intercalar PDFs',
    description: 'Combina dos PDFs alternando sus páginas A1, B1, A2, B2…',
    longDescription: 'Intercala las páginas de dos PDFs en un solo documento alternándolas: primero una página del documento A, luego una del B, y así sucesivamente. Ideal para combinar anversos y reversos escaneados por separado.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Shuffle',
    color: 'blue',
    related: ['unir-pdfs', 'reordenar-paginas-pdf', 'dividir-pdf'],
  },
  {
    slug: 'escalar-pdf',
    name: 'Escalar PDF',
    description: 'Redimensiona todas las páginas de un PDF a un tamaño estándar.',
    longDescription: 'Convierte todas las páginas de tu PDF a un tamaño estándar (A4, A3, Carta, Legal) manteniendo la proporción del contenido original. Ideal para estandarizar documentos de distintos orígenes. 100% local con pdf-lib.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Maximize2',
    color: 'blue',
    related: ['comprimir-pdf', 'rotar-pdf', 'recortar-pdf'],
  },
  {
    slug: 'encabezado-pie-pdf',
    name: 'Encabezado y pie de página PDF',
    description: 'Añade texto de encabezado y pie a todas las páginas de un PDF.',
    longDescription: 'Inserta texto personalizado en la cabecera y el pie de cada página de tu PDF. Configura el texto, tamaño de fuente y márgenes. Perfecto para añadir el nombre del documento, empresa o número de revisión.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'PanelTop',
    color: 'blue',
    related: ['numerar-paginas-pdf', 'marca-agua-pdf', 'anadir-texto-pdf'],
  },
  {
    slug: 'duplicar-paginas-pdf',
    name: 'Duplicar páginas PDF',
    description: 'Duplica páginas específicas de un PDF el número de veces que necesites.',
    longDescription: 'Selecciona qué páginas de tu PDF quieres duplicar y cuántas copias adicionales insertar. Las copias se insertan justo después de la página original. Útil para formularios, plantillas y documentos con páginas repetidas.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'CopyPlus',
    color: 'blue',
    related: ['extraer-paginas-pdf', 'unir-pdfs', 'reordenar-paginas-pdf'],
  },

  // Video
  {
    slug: 'bucle-video',
    name: 'Bucle de vídeo',
    description: 'Repite tu vídeo en bucle el número de veces que quieras.',
    longDescription: 'Crea un vídeo en bucle repitiendo el clip original N veces en un único archivo MP4. Perfecto para vídeos de fondo, loops para redes sociales y presentaciones. FFmpeg.wasm, 100% local, sin límite de tamaño.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Repeat',
    color: 'blue',
    related: ['unir-videos', 'comprimir-video', 'convertir-video'],
  },
  {
    slug: 'audio-a-video',
    name: 'Audio a vídeo',
    description: 'Convierte un audio en vídeo con imagen de fondo estática o color sólido.',
    longDescription: 'Transforma cualquier archivo de audio en un vídeo MP4 añadiendo una imagen de fondo o un color sólido. Ideal para subir podcasts, música o locuciones a plataformas de vídeo. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Music2',
    color: 'blue',
    related: ['extraer-audio', 'anadir-audio-video', 'convertir-video'],
  },
  {
    slug: 'revertir-video',
    name: 'Revertir vídeo',
    description: 'Reproduce tu vídeo al revés con el efecto reverse.',
    longDescription: 'Invierte el orden de los fotogramas de tu vídeo para reproducirlo de atrás hacia adelante. El audio también se invierte. Perfecto para efectos creativos, slow-motion inverso y contenido para redes sociales.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Rewind',
    color: 'blue',
    related: ['cambiar-velocidad', 'recortar-video', 'comprimir-video'],
  },
  {
    slug: 'reducir-fps',
    name: 'Reducir FPS de vídeo',
    description: 'Cambia la tasa de fotogramas de tu vídeo para reducir el tamaño.',
    longDescription: 'Reduce los fotogramas por segundo (FPS) de cualquier vídeo para decrementar su tamaño de archivo. Presets: 60, 30, 25, 24, 15 o FPS personalizado. Útil para vídeos web, GIFs y almacenamiento. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Timer',
    color: 'blue',
    related: ['comprimir-video', 'cambiar-velocidad', 'convertir-video'],
  },

  // Audio
  {
    slug: 'eco-audio',
    name: 'Eco en audio',
    description: 'Añade efecto de eco y reverb a tu audio con controles ajustables.',
    longDescription: 'Aplica un efecto de eco configurable a cualquier archivo de audio usando el filtro aecho de FFmpeg. Controla el retardo (ms) y el decaimiento del eco. Perfecto para producción musical, efectos de voz y podcasts creativos.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Waves',
    color: 'blue',
    related: ['cambiar-tono', 'cambiar-volumen', 'agregar-fade-audio'],
  },
  {
    slug: 'convertir-a-estereo',
    name: 'Convertir mono a estéreo',
    description: 'Convierte audio mono en estéreo duplicando el canal único.',
    longDescription: 'Transforma cualquier pista de audio mono en estéreo duplicando el canal en ambos altavoces. Compatible con MP3, WAV, OGG, AAC y FLAC. Complementario a la herramienta de conversión a mono. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Speaker',
    color: 'blue',
    related: ['convertir-a-mono', 'convertir-audio', 'comprimir-audio'],
  },
  {
    slug: 'eliminar-silencio',
    name: 'Eliminar silencios',
    description: 'Elimina automáticamente los silencios de un audio para acortarlo.',
    longDescription: 'Recorta automáticamente los fragmentos de silencio de cualquier audio usando el filtro silenceremove de FFmpeg. Configura el umbral de decibelios y la duración mínima de silencio. Ideal para podcasts, entrevistas y grabaciones de voz.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'VolumeX',
    color: 'blue',
    related: ['cortar-audio', 'cambiar-volumen', 'agregar-fade-audio'],
  },
  {
    slug: 'normalizar-audio',
    name: 'Normalizar audio',
    description: 'Normaliza el volumen de tu audio al estándar de streaming o broadcast.',
    longDescription: 'Ajusta el volumen de tu audio al nivel estándar EBU R128 usando el filtro loudnorm de FFmpeg. Presets: -14 LUFS (streaming), -16 LUFS (podcast), -23 LUFS (broadcast). Elimina variaciones de volumen entre pistas.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Activity',
    color: 'blue',
    related: ['cambiar-volumen', 'comprimir-audio', 'mezclar-audios'],
  },

  // Developer
  {
    slug: 'formateador-sql',
    name: 'Formateador SQL',
    description: 'Formatea y minifica consultas SQL con indentación automática.',
    longDescription: 'Embellece consultas SQL desordenadas con indentación automática y palabras clave en mayúsculas. También minifica SQL a una sola línea. Compatible con SELECT, INSERT, UPDATE, DELETE y JOINs complejos. Sin dependencias externas.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Database',
    color: 'blue',
    related: ['formatear-json', 'csv-a-json', 'minificador-html'],
  },
  {
    slug: 'jwt-decoder',
    name: 'Decodificador JWT',
    description: 'Decodifica y visualiza el header y payload de cualquier token JWT.',
    longDescription: 'Pega un JSON Web Token y visualiza de forma legible su cabecera (header), carga útil (payload) y la firma (signature). Decodificación base64url con soporte Unicode. La clave privada nunca es necesaria para leer el contenido.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'KeySquare',
    color: 'blue',
    related: ['calcular-hash', 'base64-texto', 'codificar-url'],
  },
  {
    slug: 'esquema-colores',
    name: 'Esquema de colores',
    description: 'Genera paletas de colores complementarias, triádicas y análogas.',
    longDescription: 'A partir de un color base, genera automáticamente esquemas de colores armoniosos: complementario, análogo, triádico, split-complementario y tetrádico. Muestra los colores con sus códigos HEX, RGB y HSL. Sin dependencias externas.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Pipette',
    color: 'blue',
    related: ['convertir-color', 'colores-imagen', 'gradiente-css'],
  },
  {
    slug: 'comparar-texto',
    name: 'Comparar texto',
    description: 'Compara dos textos línea a línea y resalta las diferencias.',
    longDescription: 'Pega dos versiones de un texto y visualiza exactamente qué líneas fueron añadidas, eliminadas o modificadas. El algoritmo LCS detecta cambios con precisión. Útil para comparar configuraciones, código o documentos.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'GitCompare',
    color: 'blue',
    related: ['regex-tester', 'contador-palabras', 'minificador-html'],
  },

  // ── NUEVAS 20 HERRAMIENTAS (2ª tanda) ────────────────────────

  // Imagen
  {
    slug: 'ruido',
    name: 'Efecto ruido',
    description: 'Añade ruido aleatorio a tu imagen para crear efectos de grano fotográfico.',
    longDescription: 'Aplica ruido aleatorio sobre cada píxel de tu imagen con control de intensidad. Disponible en modo monocromático (grano clásico) o color. Ideal para efectos vintage, film grain y texturizado artístico.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Wand2',
    color: 'purple',
    related: ['efecto-vintage', 'efecto-boceto', 'blancoynegro'],
  },
  {
    slug: 'posterizar',
    name: 'Posterizar imagen',
    description: 'Reduce los niveles de color de tu imagen con efecto póster artístico.',
    longDescription: 'La posterización cuantiza los colores de la imagen a un número limitado de niveles (2-8), creando un efecto de poster o serigrafía. Ajusta el número de niveles con un slider para diferentes intensidades del efecto.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'PenTool',
    color: 'purple',
    related: ['blancoynegro', 'efecto-duotono', 'editor'],
  },
  {
    slug: 'vigneta',
    name: 'Viñeta',
    description: 'Añade un efecto de viñetado en los bordes de la imagen.',
    longDescription: 'Aplica un gradiente radial oscuro o de color en los bordes de tu imagen para enfocar la atención en el centro. Controla la intensidad y el color del viñeteado. Efecto clásico de fotografía analógica y cine.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Eye',
    color: 'purple',
    related: ['efecto-vintage', 'desenfoque', 'editor'],
  },
  {
    slug: 'solarizar',
    name: 'Solarizar imagen',
    description: 'Aplica el efecto Sabattier (solarización) a tu imagen.',
    longDescription: 'La solarización o efecto Sabattier invierte los píxeles por encima de un umbral de luminosidad, creando un efecto fotográfico surrealista. Ajusta el umbral para controlar qué zonas se invierten y escoge entre tres presets.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Sun',
    color: 'purple',
    related: ['invertir', 'blancoynegro', 'efecto-boceto'],
  },

  // PDF
  {
    slug: 'insertar-pagina-pdf',
    name: 'Insertar páginas en PDF',
    description: 'Añade páginas en blanco dentro de un PDF en la posición que elijas.',
    longDescription: 'Inserta una o varias páginas en blanco antes o después de cualquier página de tu PDF. Útil para añadir separadores, espacio para anotaciones o páginas adicionales en un documento existente. 100% local con pdf-lib.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FileDiff',
    color: 'blue',
    related: ['eliminar-paginas-pdf', 'reordenar-paginas-pdf', 'pdf-en-blanco'],
  },
  {
    slug: 'fondo-color-pdf',
    name: 'Fondo de color en PDF',
    description: 'Añade un color de fondo a todas las páginas de un PDF.',
    longDescription: 'Aplica un color de fondo sólido a todas las páginas de tu PDF. El contenido original se preserva completamente mediante la técnica embedPage de pdf-lib. Perfecto para PDFs con fondo transparente o para añadir branding corporativo.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Square',
    color: 'blue',
    related: ['anadir-imagen-pdf', 'anadir-texto-pdf', 'marca-agua-pdf'],
  },
  {
    slug: 'aplanar-pdf',
    name: 'Aplanar PDF',
    description: 'Convierte los campos de formulario de un PDF en texto estático no editable.',
    longDescription: 'Aplana los campos interactivos de un formulario PDF (checkboxes, campos de texto, listas desplegables) convirtiéndolos en contenido estático. El documento resultante no puede ser editado mediante los campos originales. 100% local con pdf-lib.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Pin',
    color: 'blue',
    related: ['proteger-pdf', 'firmar-pdf', 'metadatos-pdf'],
  },

  // Vídeo
  {
    slug: 'convertir-vertical',
    name: 'Convertir a vídeo vertical',
    description: 'Convierte vídeos horizontales al formato 9:16 para móviles y Reels.',
    longDescription: 'Adapta cualquier vídeo horizontal (16:9) al formato vertical (9:16) o cuadrado (1:1) para redes sociales como Instagram Reels, TikTok y YouTube Shorts. Elige el color de las barras laterales. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Smartphone',
    color: 'blue',
    related: ['cambiar-resolucion-video', 'recortar-area-video', 'comprimir-video'],
  },
  {
    slug: 'boomerang-video',
    name: 'Efecto boomerang',
    description: 'Crea un boomerang: el vídeo avanza y luego retrocede en un bucle.',
    longDescription: 'Genera el clásico efecto boomerang al estilo Instagram: el vídeo se reproduce hacia adelante y luego automáticamente hacia atrás, en un bucle fluido. Configura cuántas veces se repite el ciclo. FFmpeg.wasm, 100% local.',
    category: 'Creativas',
    domain: 'video',
    icon: 'Repeat2',
    color: 'purple',
    related: ['revertir-video', 'bucle-video', 'recortar-video'],
  },
  {
    slug: 'ajustar-volumen-video',
    name: 'Ajustar volumen de vídeo',
    description: 'Sube o baja el volumen del audio de un vídeo con precisión en dB.',
    longDescription: 'Modifica el nivel de volumen del audio de cualquier vídeo entre -20 dB y +20 dB. El stream de vídeo se copia sin re-codificar para preservar la calidad original. Ideal para normalizar vídeos antes de subirlos a plataformas.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Volume1',
    color: 'blue',
    related: ['silenciar-video', 'anadir-audio-video', 'comprimir-video'],
  },

  // Audio
  {
    slug: 'ecualizador-audio',
    name: 'Ecualizador de audio',
    description: 'Ajusta graves, medios y agudos con un ecualizador de 3 bandas.',
    longDescription: 'Ecualizador paramétrico de 3 bandas: graves (bass), medios (mid) y agudos (treble). Cada banda puede ajustarse entre -20 dB y +20 dB. Incluye presets como Rock, Pop, Voz y Clásica. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'BarChart3',
    color: 'blue',
    related: ['cambiar-tono', 'cambiar-volumen', 'normalizar-audio'],
  },
  {
    slug: 'reducir-ruido-audio',
    name: 'Reducir ruido de audio',
    description: 'Elimina el ruido de fondo de tus grabaciones con filtro adaptativo.',
    longDescription: 'Reduce el ruido de fondo (ventiladores, ambiente, hiss) de grabaciones de voz, podcasts e instrumentos usando el filtro adaptativo anlmdn de FFmpeg. Tres niveles de reducción: suave, medio e intenso. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Filter',
    color: 'blue',
    related: ['normalizar-audio', 'cambiar-volumen', 'ecualizador-audio'],
  },
  {
    slug: 'generar-tono',
    name: 'Generador de tonos',
    description: 'Genera tonos de audio puro: sinusoidal, cuadrado, triangular y diente de sierra.',
    longDescription: 'Crea archivos de audio con tonos puros a la frecuencia y duración que necesites. Soporta cuatro formas de onda: sinusoidal, cuadrada, triangular y diente de sierra. Útil para pruebas de audio, calibración y efectos de sonido. FFmpeg.wasm lavfi.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Bell',
    color: 'blue',
    related: ['convertir-audio', 'mezclar-audios', 'cambiar-tono'],
  },

  // Developer (utilidades)
  {
    slug: 'conversor-base',
    name: 'Conversor de bases numéricas',
    description: 'Convierte números entre decimal, binario, hexadecimal y octal.',
    longDescription: 'Introduce un número en cualquier base (decimal, binario, hexadecimal u octal) y obtén al instante su equivalente en todas las demás. El binario se muestra agrupado en nibbles (grupos de 4 bits) para mejor legibilidad.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Terminal',
    color: 'blue',
    related: ['calcular-hash', 'base64-texto', 'codificar-url'],
  },
  {
    slug: 'entidades-html',
    name: 'Entidades HTML',
    description: 'Codifica y decodifica entidades HTML con tabla de referencia.',
    longDescription: 'Convierte texto plano a entidades HTML (&amp;, &lt;, &gt;…) y viceversa. Incluye una tabla de referencia con las 23 entidades HTML más frecuentes que puedes insertar con un clic. Sin registro, sin instalación, 100% en el navegador.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Tag',
    color: 'blue',
    related: ['codificar-url', 'minificador-html', 'formatear-json'],
  },

  // ── PDF · NUEVAS ─────────────────────────────────────────────
  {
    slug: 'metadatos-pdf',
    name: 'Metadatos de PDF',
    description: 'Visualiza y edita el título, autor, asunto y palabras clave de un PDF.',
    longDescription: 'Lee y modifica los metadatos de cualquier PDF: título, autor, asunto y palabras clave. También muestra el creador del documento y la fecha de creación. Guarda el PDF modificado con los nuevos metadatos. 100% local con pdf-lib.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Info',
    color: 'blue',
    related: ['proteger-pdf', 'eliminar-password-pdf', 'comprimir-pdf'],
  },

  // ── 20 HERRAMIENTAS NUEVAS (3ª tanda) ─────────────────────────

  // Imagen
  {
    slug: 'comparar-imagenes',
    name: 'Comparar imágenes',
    description: 'Compara dos imágenes con un slider interactivo de antes/después.',
    longDescription: 'Sube dos imágenes y compáralas con un deslizador interactivo de antes/después. Arrastra la línea divisoria para revelar cada imagen. Ideal para comparar originales con versiones editadas, filtros o retoque fotográfico.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Columns2',
    color: 'blue',
    related: ['redimensionar', 'convertir', 'editor'],
  },
  {
    slug: 'placeholder',
    name: 'Imagen placeholder',
    description: 'Genera imágenes de marcador de posición con texto, tamaño y color a medida.',
    longDescription: 'Crea imágenes placeholder con el tamaño, color de fondo y texto que necesites. Presets de proporción estándar: 16:9, 1:1, 4:3, OG (1200×630) y Banner. Descarga en PNG. Canvas API, 100% en el navegador.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'LayoutTemplate',
    color: 'blue',
    related: ['og-image', 'redimensionar', 'convertir'],
  },
  {
    slug: 'efecto-glitch',
    name: 'Efecto glitch',
    description: 'Aplica un efecto glitch RGB con desplazamiento de canales a tu imagen.',
    longDescription: 'Crea un efecto glitch artístico desplazando los canales de color R, G y B de forma independiente y añadiendo cortes horizontales aleatorios. Genera nuevas variaciones con un clic. Canvas API, 100% en el navegador.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Tv',
    color: 'purple',
    related: ['efecto-vintage', 'posterizar', 'efecto-boceto'],
  },
  {
    slug: 'tilt-shift',
    name: 'Efecto tilt-shift',
    description: 'Simula el efecto de maqueta miniatura con desenfoque tilt-shift.',
    longDescription: 'Aplica desenfoque gaussiano fuera de una banda de enfoque horizontal, simulando el efecto de lente tilt-shift que hace que las escenas parezcan maquetas en miniatura. Controla el desenfoque, la posición y el tamaño de la zona enfocada.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Focus',
    color: 'purple',
    related: ['desenfoque', 'efecto-vintage', 'vigneta'],
  },
  {
    slug: 'imagen-a-ico',
    name: 'Imagen a ICO',
    description: 'Convierte cualquier imagen a formato .ico con múltiples tamaños.',
    longDescription: 'Convierte tu imagen a un archivo .ico para favicon con los tamaños estándar que necesites: 16, 32, 48, 64, 128 y 256 px. El ICO generado usa el formato moderno con PNG embebido, compatible con todos los navegadores.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'AppWindow',
    color: 'blue',
    related: ['convertir', 'redimensionar', 'recortar'],
  },

  // PDF
  {
    slug: 'sellar-pdf',
    name: 'Sellar PDF',
    description: 'Añade un sello de texto diagonal a todas las páginas de un PDF.',
    longDescription: 'Estampa un sello de texto (BORRADOR, CONFIDENCIAL, APROBADO, RECHAZADO…) en diagonal sobre todas las páginas de tu PDF. Controla el color y la opacidad del sello. 100% local con pdf-lib. Sin subir archivos al servidor.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Stamp',
    color: 'blue',
    related: ['marca-agua-pdf', 'anadir-texto-pdf', 'proteger-pdf'],
  },
  {
    slug: 'pdf-a-svg',
    name: 'PDF a SVG',
    description: 'Convierte páginas de PDF a imágenes SVG descargables.',
    longDescription: 'Renderiza cada página de tu PDF como imagen SVG con PNG embebido. Descarga páginas individuales o todas en un ZIP. Usa pdfjs-dist para el renderizado y un conversor ZIP puro en el navegador. Sin subir archivos.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Spline',
    color: 'blue',
    related: ['pdf-a-imagen', 'pdf-a-texto', 'comprimir-pdf'],
  },
  {
    slug: 'comparar-pdfs',
    name: 'Comparar PDFs',
    description: 'Compara dos PDFs página a página en una vista sincronizada.',
    longDescription: 'Visualiza dos PDFs en paralelo con navegación sincronizada. Navega por las páginas de ambos documentos a la vez y compara su contenido visualmente. Escala ajustable. pdfjs-dist, 100% en el navegador. Sin subir archivos.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FileDiff',
    color: 'blue',
    related: ['comparar-texto', 'unir-pdf', 'extraer-paginas-pdf'],
  },
  {
    slug: 'indice-pdf',
    name: 'Índice de PDF',
    description: 'Extrae el índice y marcadores de un PDF con números de página.',
    longDescription: 'Obtén el índice o tabla de contenidos de cualquier PDF con los números de página correspondientes. Si el PDF tiene marcadores integrados, los usa directamente; si no, detecta automáticamente los encabezados por tamaño de fuente.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'ListTree',
    color: 'blue',
    related: ['pdf-a-texto', 'extraer-paginas-pdf', 'metadatos-pdf'],
  },

  // Vídeo
  {
    slug: 'anadir-subtitulos',
    name: 'Añadir subtítulos',
    description: 'Incrusta subtítulos de un archivo SRT en tu vídeo permanentemente.',
    longDescription: 'Carga un vídeo y un archivo de subtítulos .SRT para incrustar los subtítulos directamente en los fotogramas del vídeo. Los subtítulos se renderizan en canvas y se superponen con FFmpeg.wasm. Sin servidores externos.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Subtitles',
    color: 'blue',
    related: ['marca-agua-video', 'recortar-video', 'comprimir-video'],
  },
  {
    slug: 'extraer-fotogramas',
    name: 'Extraer fotogramas',
    description: 'Extrae todos los fotogramas de un vídeo como imágenes y los descarga en ZIP.',
    longDescription: 'Exporta fotogramas de tu vídeo a la tasa de FPS que elijas (0.5, 1, 2 o 5 fps) en formato JPG o PNG. Los fotogramas se descargan comprimidos en un archivo ZIP. FFmpeg.wasm, 100% local. Sin subir archivos al servidor.',
    category: 'Avanzadas',
    domain: 'video',
    icon: 'GalleryHorizontal',
    color: 'purple',
    related: ['miniatura-video', 'recortar-video', 'gif-desde-video'],
  },
  {
    slug: 'ajuste-color-video',
    name: 'Ajuste de color de vídeo',
    description: 'Ajusta brillo, contraste, saturación y gamma de tu vídeo.',
    longDescription: 'Mejora o transforma el aspecto visual de tu vídeo con cuatro controles de color: brillo, contraste, saturación y gamma. Incluye presets: Original, Vivid, Cine, Vintage y Blanco y negro. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Settings2',
    color: 'blue',
    related: ['comprimir-video', 'convertir-video', 'recortar-video'],
  },
  {
    slug: 'miniatura-video',
    name: 'Miniatura de vídeo',
    description: 'Captura cualquier fotograma de tu vídeo como imagen PNG o JPG.',
    longDescription: 'Selecciona el instante exacto de tu vídeo con un slider y descarga ese fotograma como imagen en PNG o JPG. Usa la API nativa de vídeo HTML5 y Canvas, sin FFmpeg ni servidores externos. Rápido e instantáneo.',
    category: 'Básicas',
    domain: 'video',
    icon: 'MonitorPlay',
    color: 'blue',
    related: ['extraer-fotogramas', 'gif-desde-video', 'recortar-video'],
  },
  {
    slug: 'fundido-video',
    name: 'Fundido a negro',
    description: 'Añade un fundido de entrada y/o salida a negro en tu vídeo.',
    longDescription: 'Aplica una transición suave de negro al vídeo (fade in) y del vídeo al negro (fade out). Configura la duración de cada fundido de forma independiente entre 0.5 y 2 segundos. El efecto se aplica al vídeo y al audio simultáneamente. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Sunset',
    color: 'blue',
    related: ['comprimir-video', 'recortar-video', 'boomerang-video'],
  },
  {
    slug: 'escala-grises-video',
    name: 'Escala de grises en vídeo',
    description: 'Convierte tu vídeo a escala de grises, sepia o negativo.',
    longDescription: 'Aplica efectos de color a tu vídeo: escala de grises clásica (blanco y negro), tono sepia cálido vintage o negativo invertido. El audio se conserva sin cambios. FFmpeg.wasm, 100% local, sin subir archivos.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Blend',
    color: 'blue',
    related: ['ajuste-color-video', 'comprimir-video', 'convertir-video'],
  },
  {
    slug: 'fotogramas-a-video',
    name: 'Fotos a vídeo',
    description: 'Crea un vídeo slideshow a partir de varias imágenes.',
    longDescription: 'Convierte una colección de fotos en un vídeo MP4 con transición directa entre imágenes. Configura la duración de cada foto (1, 2, 3 o 5 segundos), la resolución de salida (720p o 1080p) y el orden arrastrando las miniaturas. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'video',
    icon: 'ImagePlay',
    color: 'blue',
    related: ['audio-a-video', 'bucle-video', 'comprimir-video'],
  },
  {
    slug: 'gif-a-video',
    name: 'GIF a MP4',
    description: 'Convierte un GIF animado a vídeo MP4 para compartir en redes.',
    longDescription: 'Transforma cualquier GIF animado en un archivo MP4 compatible con todas las plataformas. Los MP4 son hasta 10 veces más ligeros que los GIFs con la misma calidad visual. FFmpeg.wasm, 100% local. El resultado es un vídeo silencioso en H.264.',
    category: 'Básicas',
    domain: 'video',
    icon: 'MonitorPlay',
    color: 'blue',
    related: ['video-a-gif', 'comprimir-video', 'convertir-video'],
  },
  {
    slug: 'denoise-video',
    name: 'Reducir ruido de vídeo',
    description: 'Elimina el grano y ruido digital de tus vídeos con tres niveles de intensidad.',
    longDescription: 'Aplica el filtro hqdn3d de FFmpeg para reducir el ruido digital en vídeos grabados con poca luz o cámaras de baja calidad. Tres niveles de intensidad: Suave (preserva el detalle), Medio (equilibrio ideal) e Intenso (grano fuerte). FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Wand2',
    color: 'blue',
    related: ['ajuste-color-video', 'comprimir-video', 'convertir-video'],
  },

  // Audio
  {
    slug: 'detector-bpm',
    name: 'Detector de BPM',
    description: 'Detecta el tempo en BPM de cualquier archivo de audio automáticamente.',
    longDescription: 'Analiza el tempo de tu canción o pista de audio y calcula los BPM (pulsaciones por minuto) usando análisis de energía y detección de onsets con la Web Audio API. Sin modelos de IA, sin servidores. 100% local en el navegador.',
    category: 'Avanzadas',
    domain: 'audio',
    icon: 'Drum',
    color: 'purple',
    related: ['cambiar-tono', 'afinar-audio', 'mezclar-audios'],
  },
  {
    slug: 'separar-voz',
    name: 'Separar voz',
    description: 'Separa la voz de la música de fondo de un audio en dos pistas.',
    longDescription: 'Extrae la voz central y el instrumental de cualquier grabación estéreo usando el algoritmo de cancelación de canal central de FFmpeg. Obtén dos archivos: vocals y música. FFmpeg.wasm, 100% local. Sin subir archivos.',
    category: 'Avanzadas',
    domain: 'audio',
    icon: 'Mic',
    color: 'purple',
    related: ['mezclar-audios', 'detector-bpm', 'convertir-a-mono'],
  },
  {
    slug: 'transcribir-audio',
    name: 'Transcribir audio',
    description: 'Transcribe voz a texto en tiempo real usando el micrófono.',
    longDescription: 'Convierte voz a texto usando la Web Speech API del navegador. Soporta español, inglés, francés, alemán, italiano, portugués y catalán. Transcripción continua con resultados en tiempo real. Descarga el texto o cópialo al portapapeles.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'MessageSquare',
    color: 'blue',
    related: ['grabar-audio', 'convertir-audio', 'separar-voz'],
  },
  {
    slug: 'afinar-audio',
    name: 'Afinar audio',
    description: 'Desplaza el tono de tu audio en semitonos preservando la velocidad.',
    longDescription: 'Cambia el tono musical de tu audio de -12 a +12 semitonos con la opción de preservar la duración original mediante time-stretching (filtro atempo). Añade también un efecto vibrato opcional. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Music',
    color: 'blue',
    related: ['cambiar-tono', 'detector-bpm', 'normalizar-audio'],
  },

  // ── AUDIO · 19 NUEVAS ─────────────────────────────────────────
  {
    slug: 'visualizar-forma-onda',
    name: 'Visualizar forma de onda',
    description: 'Genera una imagen PNG de la forma de onda de tu audio.',
    longDescription: 'Convierte cualquier archivo de audio en una imagen visual de su forma de onda. Personaliza el color de la onda y del fondo. Descarga como PNG. Web Audio API + Canvas, 100% en el navegador, sin servidores.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'AudioLines',
    color: 'blue',
    related: ['analizar-espectro', 'detectar-tono', 'medir-duracion'],
  },
  {
    slug: 'convertir-a-m4a',
    name: 'Convertir a M4A',
    description: 'Convierte cualquier audio al formato M4A (AAC) compatible con iPhone.',
    longDescription: 'Transforma tu audio a formato M4A, el estándar de Apple para audio AAC. Compatible con iPhone, iPad, iTunes y la mayoría de reproductores modernos. Tres calidades: 128k, 192k y 320k. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Music',
    color: 'blue',
    related: ['convertir-audio', 'convertir-a-flac', 'comprimir-audio'],
  },
  {
    slug: 'robotizar-voz',
    name: 'Robotizar voz',
    description: 'Aplica efecto de voz robótica y metálica a cualquier audio.',
    longDescription: 'Transforma cualquier voz o audio con efectos de voz robótica. Elige entre presets: Robot estándar, Robot grave, Alien y Cibernético. Basado en combinaciones de eco corto, modulación y cambio de pitch. FFmpeg.wasm, 100% local.',
    category: 'Creativas',
    domain: 'audio',
    icon: 'Bot',
    color: 'purple',
    related: ['distorsion-audio', 'coro-audio', 'telefono-audio'],
  },
  {
    slug: 'dividir-audio',
    name: 'Dividir audio en dos',
    description: 'Divide un audio en dos partes en el punto de tiempo que elijas.',
    longDescription: 'Corta cualquier archivo de audio en exactamente dos partes especificando el punto de división en segundos. Descarga ambas partes de forma independiente. FFmpeg.wasm, 100% local. Sin registro, sin subir archivos.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Scissors',
    color: 'blue',
    related: ['cortar-audio', 'audio-a-fragmentos', 'recortar-silencio-inicio'],
  },
  {
    slug: 'audio-a-fragmentos',
    name: 'Audio a fragmentos',
    description: 'Divide un audio en N fragmentos de igual duración automáticamente.',
    longDescription: 'Divide cualquier audio en 2 a 10 fragmentos de duración idéntica con un solo clic. Descarga cada fragmento por separado. Ideal para cortar canciones en partes iguales, capítulos o bloques. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'LayoutGrid',
    color: 'blue',
    related: ['dividir-audio', 'cortar-audio', 'unir-audios'],
  },
  {
    slug: 'recortar-silencio-inicio',
    name: 'Recortar silencio inicio/fin',
    description: 'Elimina el silencio del principio y del final de un audio.',
    longDescription: 'Elimina automáticamente los silencios del inicio y del final de un audio, manteniendo intacto el contenido interior. A diferencia del eliminador de silencios general, este solo actúa en los extremos del archivo. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'ArrowDownToLine',
    color: 'blue',
    related: ['eliminar-silencio', 'dividir-audio', 'cortar-audio'],
  },
  {
    slug: 'insertar-audio',
    name: 'Insertar audio',
    description: 'Inserta un audio dentro de otro en el punto de tiempo que elijas.',
    longDescription: 'Toma dos archivos de audio e inserta el segundo dentro del primero en el tiempo que especifiques. El audio original se divide en ese punto y el audio insertado queda entre las dos partes. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'ListPlus',
    color: 'blue',
    related: ['reemplazar-segmento', 'unir-audios', 'mezclar-audios'],
  },
  {
    slug: 'reemplazar-segmento',
    name: 'Reemplazar segmento',
    description: 'Silencia un fragmento de tiempo específico de un archivo de audio.',
    longDescription: 'Reemplaza un intervalo de tiempo de tu audio con silencio. Perfecto para censurar palabras, eliminar ruidos puntuales o silenciar partes indeseadas. Define el inicio y fin del segmento en segundos. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Replace',
    color: 'blue',
    related: ['insertar-audio', 'cortar-audio', 'eliminar-silencio'],
  },
  {
    slug: 'audio-a-base64',
    name: 'Audio a Base64',
    description: 'Convierte un archivo de audio a cadena Base64 o data URI.',
    longDescription: 'Codifica cualquier archivo de audio en Base64 y obtén la cadena o el data URI completo listo para usar en HTML, CSS o JavaScript. También decodifica de Base64 a archivo descargable. Sin servidores, 100% en el navegador.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Binary',
    color: 'blue',
    related: ['imagen-a-base64', 'convertir-audio', 'medir-duracion'],
  },
  {
    slug: 'convertir-a-flac',
    name: 'Convertir a FLAC',
    description: 'Convierte cualquier audio al formato FLAC sin pérdida de calidad.',
    longDescription: 'Transforma tu audio a FLAC (Free Lossless Audio Codec), el formato de audio sin pérdida más compatible. Ideal para archivos máster, música de alta fidelidad y almacenamiento permanente. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Waves',
    color: 'blue',
    related: ['convertir-audio', 'convertir-a-m4a', 'comprimir-audio'],
  },
  {
    slug: 'analizar-espectro',
    name: 'Analizar espectro',
    description: 'Visualiza el espectro de frecuencias de tu audio como gráfica descargable.',
    longDescription: 'Analiza y visualiza el espectro de frecuencias de cualquier audio. Muestra la energía de cada banda de frecuencia en una gráfica de barras descargable como PNG. Web Audio API + Canvas, sin servidores.',
    category: 'Avanzadas',
    domain: 'audio',
    icon: 'BarChart3',
    color: 'purple',
    related: ['visualizar-forma-onda', 'detectar-tono', 'medir-duracion'],
  },
  {
    slug: 'detectar-tono',
    name: 'Detectar tono',
    description: 'Detecta la nota musical y frecuencia dominante de un audio.',
    longDescription: 'Analiza un archivo de audio y detecta su tono o nota musical dominante usando el algoritmo de autocorrelación. Muestra la frecuencia en Hz, la nota musical (Do, Re, Mi…) y la octava. Web Audio API, 100% en el navegador.',
    category: 'Avanzadas',
    domain: 'audio',
    icon: 'Target',
    color: 'purple',
    related: ['analizar-espectro', 'visualizar-forma-onda', 'cambiar-tono'],
  },
  {
    slug: 'medir-duracion',
    name: 'Medir duración y metadata',
    description: 'Muestra duración, sample rate, canales y bitrate de un audio.',
    longDescription: 'Analiza un archivo de audio y muestra información detallada: duración exacta, frecuencia de muestreo, número de canales, bitrate estimado y tamaño del archivo. Sin servidores, todo en el navegador con Web Audio API.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Timer',
    color: 'blue',
    related: ['visualizar-forma-onda', 'analizar-espectro', 'convertir-audio'],
  },
  {
    slug: 'cambiar-pitch-sin-tempo',
    name: 'Cambiar pitch sin cambiar tempo',
    description: 'Ajusta el tono en centésimas de semitono sin cambiar la velocidad.',
    longDescription: 'Ajusta el tono de tu audio con precisión de centésimas de semitono (±1200 cents = ±1 octava) sin alterar la duración ni la velocidad de reproducción. Ideal para afinar grabaciones y transponer con precisión milimétrica. FFmpeg.wasm.',
    category: 'Avanzadas',
    domain: 'audio',
    icon: 'TrendingUp',
    color: 'purple',
    related: ['cambiar-tono', 'afinar-audio', 'velocidad-audio'],
  },
  {
    slug: 'compresor-audio',
    name: 'Compresor de audio',
    description: 'Aplica compresión dinámica para nivelar picos de volumen.',
    longDescription: 'Controla la dinámica de tu audio con un compresor profesional. Ajusta umbral, ratio, ataque, release y ganancia de maquillaje. Presets: Suave, Podcast, Máster y Heavy. FFmpeg acompressor, 100% local.',
    category: 'Avanzadas',
    domain: 'audio',
    icon: 'Gauge',
    color: 'purple',
    related: ['normalizar-audio', 'cambiar-volumen', 'ecualizador-audio'],
  },
  {
    slug: 'distorsion-audio',
    name: 'Distorsión de audio',
    description: 'Aplica distorsión, overdrive y bitcrush a tu audio.',
    longDescription: 'Añade distorsión creativa a cualquier audio. Elige entre overdrive suave, distorsión de guitarra, efecto bitcrush de 8 bits y distorsión heavy. Ideal para producción musical, efectos de sonido y diseño sonoro. FFmpeg.wasm, 100% local.',
    category: 'Creativas',
    domain: 'audio',
    icon: 'Zap',
    color: 'purple',
    related: ['robotizar-voz', 'telefono-audio', 'coro-audio'],
  },
  {
    slug: 'coro-audio',
    name: 'Efecto coro',
    description: 'Añade efecto chorus para dar profundidad y amplitud al audio.',
    longDescription: 'Aplica el efecto de coro (chorus) que duplica y desafina ligeramente el audio para crear sensación de múltiples voces o instrumentos. Elige entre presets: Sutil, Estándar y Rico. FFmpeg achorus, 100% local.',
    category: 'Creativas',
    domain: 'audio',
    icon: 'Users2',
    color: 'purple',
    related: ['eco-audio', 'robotizar-voz', 'distorsion-audio'],
  },
  {
    slug: 'telefono-audio',
    name: 'Efecto teléfono',
    description: 'Simula el sonido de teléfono, radio AM o intercomunicador.',
    longDescription: 'Aplica filtros de banda de frecuencia para simular el sonido de una llamada telefónica (300-3400 Hz), una radio AM o un intercomunicador. Añade la característica saturación de los dispositivos de audio de banda estrecha. FFmpeg.wasm, 100% local.',
    category: 'Creativas',
    domain: 'audio',
    icon: 'Phone',
    color: 'purple',
    related: ['distorsion-audio', 'robotizar-voz', 'eco-audio'],
  },
  {
    slug: 'generar-ruido-blanco',
    name: 'Generar ruido blanco',
    description: 'Genera ruido blanco, rosa o marrón de la duración que necesites.',
    longDescription: 'Crea archivos de audio de ruido blanco, rosa (pink) o marrón (brown) de cualquier duración. Útil para masking de sonido, pruebas de audio, meditación y sleep sounds. FFmpeg lavfi anoisesrc, 100% local. Sin subir archivos.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Radio',
    color: 'blue',
    related: ['generar-tono', 'mezclar-audios', 'cambiar-volumen'],
  },

  // Developer
  {
    slug: 'minificador-svg',
    name: 'Minificador SVG',
    description: 'Elimina metadatos y atributos innecesarios de archivos SVG.',
    longDescription: 'Reduce el tamaño de tus SVGs eliminando comentarios, metadatos, atributos de Inkscape/Sodipodi/RDF y espacios innecesarios. Pega el código SVG o sube un archivo. Muestra el porcentaje de reducción. Sin dependencias externas.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'PackageMinus',
    color: 'blue',
    related: ['minificador-html', 'minificador-js', 'formatear-json'],
  },
  {
    slug: 'og-image',
    name: 'Generador OG Image',
    description: 'Crea imágenes Open Graph 1200×630 para compartir en redes sociales.',
    longDescription: 'Diseña imágenes Open Graph (og:image) de 1200×630 px con título, subtítulo, colores personalizables y logo opcional. Descarga en PNG o JPG listo para usar en tu web. Canvas API, 100% en el navegador. Sin subir archivos.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Share2',
    color: 'blue',
    related: ['placeholder', 'imagen-a-ico', 'marca-de-agua'],
  },
  {
    slug: 'convertir-fuente',
    name: 'Convertir fuente',
    description: 'Convierte fuentes entre TTF, OTF y WOFF sin perder datos.',
    longDescription: 'Convierte archivos de fuente tipográfica entre los formatos TTF, OTF y WOFF directamente en el navegador. La conversión TTF/OTF ↔ WOFF es sin pérdida: todas las tablas SFNT se preservan íntegras. Sin subir archivos al servidor.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'ALargeSmall',
    color: 'blue',
    related: ['minificador-svg', 'og-image', 'imagen-a-ico'],
  },
];

export const TOOL_BY_SLUG: Record<string, ToolMeta> = Object.fromEntries(
  TOOLS.map((t) => [t.slug, t]),
);

export const ACCEPTED_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/gif'];
export const MAX_FILE_SIZE = 50 * 1024 * 1024; // 50 MB
