export type ToolCategory = 'Básicas' | 'Creativas' | 'Avanzadas';
export type ToolDomain = 'imagen' | 'pdf' | 'developer' | 'video' | 'audio';

export interface ToolMeta {
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  category: ToolCategory;
  domain: ToolDomain;
  icon: string;
  color: string;
  related: string[];
}

export const TOOLS: ToolMeta[] = [
  // ── IMAGEN · BÁSICAS ─────────────────────────────────────────
  {
    slug: 'comprimir',
    name: 'Comprimir imagen',
    description: 'Reduce el peso de tus imágenes sin perder calidad visible.',
    longDescription: 'Comprime imágenes JPG, PNG y WebP directamente en tu navegador. Visualiza la comparativa de tamaño antes y después con una barra de progreso en tiempo real.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Minimize2',
    color: 'blue',
    related: ['convertir', 'redimensionar', 'editor'],
  },
  {
    slug: 'redimensionar',
    name: 'Redimensionar imagen',
    description: 'Cambia el tamaño por píxeles exactos o porcentaje.',
    longDescription: 'Ajusta el ancho y alto de tu imagen con precisión. Mantén la proporción con un lock de aspect ratio o introduce dimensiones personalizadas.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Scaling',
    color: 'blue',
    related: ['recortar', 'comprimir', 'convertir'],
  },
  {
    slug: 'recortar',
    name: 'Recortar imagen',
    description: 'Selecciona y recorta el área exacta que necesitas.',
    longDescription: 'Usa el área arrastrable para seleccionar la zona de recorte. Elige entre presets populares como 1:1, 16:9, 4:3 o 9:16.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Crop',
    color: 'blue',
    related: ['redimensionar', 'girar', 'comprimir'],
  },
  {
    slug: 'convertir',
    name: 'Convertir formato',
    description: 'Convierte entre JPG, PNG, WebP y AVIF al instante.',
    longDescription: 'Cambia el formato de tu imagen con un clic. Soporte para JPG, PNG, WebP y AVIF. Ve el tamaño estimado del output antes de convertir.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'RefreshCw',
    color: 'blue',
    related: ['comprimir', 'redimensionar', 'editor'],
  },
  {
    slug: 'girar',
    name: 'Girar imagen',
    description: 'Rota y voltea tu imagen con preview en tiempo real.',
    longDescription: 'Gira tu imagen 90°, 180° o 270°. Voltéala horizontal o verticalmente. El preview se actualiza en tiempo real.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'RotateCw',
    color: 'blue',
    related: ['recortar', 'redimensionar', 'editor'],
  },
  {
    slug: 'redondear',
    name: 'Redondear esquinas',
    description: 'Añade esquinas redondeadas y exporta como PNG transparente.',
    longDescription: 'Aplica un radio de esquinas ajustable a tu imagen. El resultado se exporta como PNG con fondo transparente, ideal para avatares, logos y redes sociales.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Radius',
    color: 'blue',
    related: ['recorte-circular', 'marco', 'recortar'],
  },
  {
    slug: 'recorte-circular',
    name: 'Recorte circular',
    description: 'Recorta tu imagen en forma de círculo o elipse.',
    longDescription: 'Convierte cualquier imagen en un círculo o elipse perfecta. Exporta como PNG con fondo transparente. Ideal para fotos de perfil y avatares.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'CircleDashed',
    color: 'blue',
    related: ['redondear', 'recortar', 'marco'],
  },
  {
    slug: 'marco',
    name: 'Añadir marco',
    description: 'Rodea tu imagen con un marco de color y grosor ajustables.',
    longDescription: 'Añade un borde o marco a tu imagen eligiendo color, grosor y estilo. Perfecto para destacar fotos, crear capturas con bordes o preparar imágenes para publicaciones.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Frame',
    color: 'blue',
    related: ['redondear', 'sombra', 'editor'],
  },
  {
    slug: 'desenfoque',
    name: 'Desenfocar imagen',
    description: 'Aplica desenfoque gaussiano con intensidad ajustable.',
    longDescription: 'Desenfoca tu imagen con efecto gaussiano. Controla la intensidad del desenfoque para crear fondos borrosos, proteger información o aplicar efectos artísticos.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Aperture',
    color: 'blue',
    related: ['pixelar', 'editor', 'invertir'],
  },
  // ── IMAGEN · CREATIVAS ───────────────────────────────────────
  {
    slug: 'marca-de-agua',
    name: 'Marca de agua',
    description: 'Añade texto o imagen con opacidad y posición ajustables.',
    longDescription: 'Protege tus imágenes añadiendo una marca de agua de texto o imagen. Controla la opacidad, posición (9 puntos de anclaje) y tamaño.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Droplets',
    color: 'purple',
    related: ['meme', 'editor', 'comprimir'],
  },
  {
    slug: 'meme',
    name: 'Creador de memes',
    description: 'Crea memes con texto superior e inferior estilo clásico.',
    longDescription: 'Añade texto superior e inferior con fuente Impact y outline negro. Ajusta el tamaño y crea memes en segundos.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Laugh',
    color: 'purple',
    related: ['marca-de-agua', 'editor', 'comprimir'],
  },
  {
    slug: 'blancoynegro',
    name: 'Blanco y negro',
    description: 'Convierte tu imagen a escala de grises con ajuste de contraste.',
    longDescription: 'Transforma tus fotos a blanco y negro con control de brillo y contraste. Resultado profesional con la ponderación luminosa correcta (Rec. 709).',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Contrast',
    color: 'purple',
    related: ['invertir', 'editor', 'comprimir'],
  },
  {
    slug: 'invertir',
    name: 'Invertir colores',
    description: 'Aplica el efecto negativo invirtiendo todos los colores.',
    longDescription: 'Invierte los valores de color de tu imagen creando un efecto negativo. Útil para efectos artísticos, análisis de imágenes y creación de negativos fotográficos.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'SunMoon',
    color: 'purple',
    related: ['blancoynegro', 'editor', 'desenfoque'],
  },
  {
    slug: 'paleta',
    name: 'Extraer paleta de colores',
    description: 'Detecta los colores dominantes de cualquier imagen.',
    longDescription: 'Analiza tu imagen y extrae la paleta de colores dominantes. Obtén los códigos hexadecimales, cópialos al portapapeles y descarga la paleta como imagen.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Palette',
    color: 'purple',
    related: ['editor', 'blancoynegro', 'invertir'],
  },
  {
    slug: 'collage',
    name: 'Crear collage',
    description: 'Combina varias imágenes en una sola con diseños de cuadrícula.',
    longDescription: 'Sube entre 2 y 4 imágenes y combínalas en un collage con diferentes diseños de cuadrícula. Ajusta el espaciado y el color de fondo.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'LayoutGrid',
    color: 'purple',
    related: ['marco', 'redimensionar', 'comprimir'],
  },
  {
    slug: 'texto',
    name: 'Añadir texto',
    description: 'Escribe texto sobre tu imagen con fuente, color y posición.',
    longDescription: 'Añade texto personalizado a tu imagen con control sobre fuente, tamaño, color, contorno y posición. Perfecto para subtítulos, etiquetas y títulos.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Type',
    color: 'purple',
    related: ['marca-de-agua', 'meme', 'marco'],
  },
  // ── IMAGEN · AVANZADAS ───────────────────────────────────────
  {
    slug: 'editor',
    name: 'Editor de imagen',
    description: 'Ajusta brillo, contraste, saturación y aplica presets.',
    longDescription: 'Editor completo con controles de brillo, contraste, saturación, temperatura y nitidez. Incluye 6 presets: vintage, blanco y negro, vivid, fade, cinematic y cool.',
    category: 'Avanzadas',
    domain: 'imagen',
    icon: 'Sliders',
    color: 'orange',
    related: ['comprimir', 'convertir', 'girar'],
  },
  {
    slug: 'eliminar-fondo',
    name: 'Eliminar fondo (IA)',
    description: 'Elimina el fondo de tus fotos con inteligencia artificial.',
    longDescription: 'Usa IA para eliminar el fondo de forma automática. Descarga con fondo transparente (PNG) o elige un color de fondo sólido.',
    category: 'Avanzadas',
    domain: 'imagen',
    icon: 'Scissors',
    color: 'orange',
    related: ['editor', 'comprimir', 'convertir'],
  },
  {
    slug: 'html-a-imagen',
    name: 'HTML a imagen',
    description: 'Convierte código HTML y CSS en una imagen PNG o JPG.',
    longDescription: 'Escribe o pega código HTML con estilos CSS y captúralo como imagen. Ideal para crear OG images, banners o capturas de componentes.',
    category: 'Avanzadas',
    domain: 'imagen',
    icon: 'Code',
    color: 'orange',
    related: ['meme', 'marca-de-agua', 'editor'],
  },
  {
    slug: 'pixelar',
    name: 'Pixelar imagen',
    description: 'Censura zonas específicas o aplica efecto pixel art.',
    longDescription: 'Selecciona con el ratón la zona a pixelar y ajusta la intensidad con un slider. Perfecto para censurar caras, datos sensibles o crear efectos retro.',
    category: 'Avanzadas',
    domain: 'imagen',
    icon: 'Grid3x3',
    color: 'orange',
    related: ['recortar', 'editor', 'comprimir'],
  },
  {
    slug: 'sombra',
    name: 'Añadir sombra',
    description: 'Añade una sombra paralela a tu imagen con fondo transparente.',
    longDescription: 'Agrega una sombra de tipo drop shadow a tu imagen. Ajusta el desplazamiento, el desenfoque y el color. Exporta como PNG con fondo transparente.',
    category: 'Avanzadas',
    domain: 'imagen',
    icon: 'Layers',
    color: 'orange',
    related: ['marco', 'redondear', 'editor'],
  },

  // ── PDF · BÁSICAS ─────────────────────────────────────────────
  {
    slug: 'comprimir-pdf',
    name: 'Comprimir PDF',
    description: 'Reduce el tamaño de tu PDF conservando la calidad del texto.',
    longDescription: 'Comprime archivos PDF directamente en el navegador usando recodificación de objetos. Sin servidores, sin límites de tamaño. Ideal para adjuntar PDFs en emails o formularios con límite de peso.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FileDown',
    color: 'blue',
    related: ['unir-pdfs', 'dividir-pdf', 'pdf-a-jpg'],
  },
  {
    slug: 'unir-pdfs',
    name: 'Unir PDFs',
    description: 'Combina varios archivos PDF en uno solo conservando el orden.',
    longDescription: 'Fusiona múltiples PDFs en un único documento. Reordena los archivos arrastrando antes de unirlos. Sin límite de archivos y sin enviar nada al servidor.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Files',
    color: 'blue',
    related: ['dividir-pdf', 'comprimir-pdf', 'extraer-paginas-pdf'],
  },
  {
    slug: 'dividir-pdf',
    name: 'Dividir PDF',
    description: 'Divide un PDF en partes o extrae un rango de páginas.',
    longDescription: 'Divide un PDF en páginas individuales o extrae un rango específico como nuevo documento. Perfecto para separar informes, contratos o capítulos sin software adicional.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FileMinus2',
    color: 'blue',
    related: ['unir-pdfs', 'extraer-paginas-pdf', 'comprimir-pdf'],
  },
  {
    slug: 'pdf-a-jpg',
    name: 'PDF a JPG',
    description: 'Convierte cada página de tu PDF en una imagen JPG.',
    longDescription: 'Renderiza cada página de un PDF como imagen JPG de alta calidad directamente en el navegador con PDF.js. Descarga las imágenes individualmente o todas de una vez.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FileImage',
    color: 'blue',
    related: ['jpg-a-pdf', 'comprimir-pdf', 'dividir-pdf'],
  },
  {
    slug: 'jpg-a-pdf',
    name: 'JPG a PDF',
    description: 'Convierte una o varias imágenes en un documento PDF.',
    longDescription: 'Transforma imágenes JPG, PNG o WebP en un PDF listo para imprimir o compartir. Selecciona el tamaño de página (A4, Carta o automático) y ajusta la orientación.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FilePlus2',
    color: 'blue',
    related: ['pdf-a-jpg', 'unir-pdfs', 'comprimir-pdf'],
  },
  {
    slug: 'rotar-pdf',
    name: 'Rotar PDF',
    description: 'Gira las páginas de tu PDF 90°, 180° o 270°.',
    longDescription: 'Corrige la orientación de páginas escaneadas o rotadas en un PDF. Aplica la rotación a todas las páginas o elige páginas específicas. El resultado se descarga al instante.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'RotateCcw',
    color: 'blue',
    related: ['comprimir-pdf', 'dividir-pdf', 'extraer-paginas-pdf'],
  },
  {
    slug: 'extraer-paginas-pdf',
    name: 'Extraer páginas PDF',
    description: 'Selecciona y extrae páginas concretas de un PDF.',
    longDescription: 'Introduce el rango de páginas que quieres conservar (por ejemplo: 1-3, 5, 8-10) y genera un nuevo PDF con solo esas páginas. Sin instalación ni registro.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'BookOpen',
    color: 'blue',
    related: ['dividir-pdf', 'unir-pdfs', 'comprimir-pdf'],
  },
  // ── PDF · AVANZADAS ───────────────────────────────────────────
  {
    slug: 'extraer-texto-pdf',
    name: 'Extraer texto de PDF',
    description: 'Copia todo el texto de un PDF en segundos.',
    longDescription: 'Extrae el contenido textual de cualquier PDF directamente en el navegador usando PDF.js. Descarga el resultado como archivo .txt o cópialo al portapapeles.',
    category: 'Avanzadas',
    domain: 'pdf',
    icon: 'FileText',
    color: 'orange',
    related: ['dividir-pdf', 'extraer-paginas-pdf', 'proteger-pdf'],
  },
  {
    slug: 'proteger-pdf',
    name: 'Proteger PDF',
    description: 'Añade contraseña a un PDF para proteger su contenido.',
    longDescription: 'Cifra tu PDF con contraseña de usuario para que solo quien la conozca pueda abrirlo. Opcionalmente añade contraseña de propietario para restricciones de edición e impresión.',
    category: 'Avanzadas',
    domain: 'pdf',
    icon: 'Lock',
    color: 'orange',
    related: ['eliminar-password-pdf', 'comprimir-pdf', 'unir-pdfs'],
  },
  {
    slug: 'eliminar-password-pdf',
    name: 'Eliminar contraseña PDF',
    description: 'Desbloquea un PDF protegido con contraseña.',
    longDescription: 'Si conoces la contraseña de un PDF, puedes eliminarla y guardar el archivo desbloqueado. El proceso es 100% local: la contraseña nunca se envía a ningún servidor.',
    category: 'Avanzadas',
    domain: 'pdf',
    icon: 'Unlock',
    color: 'orange',
    related: ['proteger-pdf', 'comprimir-pdf', 'extraer-texto-pdf'],
  },

  // ── VIDEO · BÁSICAS ──────────────────────────────────────────
  {
    slug: 'comprimir-video',
    name: 'Comprimir vídeo',
    description: 'Reduce el tamaño de tu vídeo ajustando la calidad de compresión.',
    longDescription: 'Comprime tus vídeos MP4 y WebM directamente en el navegador con FFmpeg.wasm. Ajusta el nivel de calidad CRF para encontrar el equilibrio ideal entre tamaño y calidad visual.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Video',
    color: 'blue',
    related: ['convertir-video', 'recortar-video', 'extraer-audio'],
  },
  {
    slug: 'convertir-video',
    name: 'Convertir vídeo',
    description: 'Convierte entre MP4 y WebM sin perder calidad.',
    longDescription: 'Cambia el formato de tu vídeo entre MP4 (H.264) y WebM (VP8) sin instalar nada. El procesamiento es 100% local con FFmpeg.wasm.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Film',
    color: 'blue',
    related: ['comprimir-video', 'recortar-video', 'extraer-audio'],
  },
  {
    slug: 'extraer-audio',
    name: 'Extraer audio de vídeo',
    description: 'Extrae la pista de audio de cualquier vídeo como MP3 o WAV.',
    longDescription: 'Obtén solo el audio de un vídeo MP4 o WebM. Descarga el resultado como MP3 (comprimido) o WAV (sin pérdida). Procesamiento 100% local con FFmpeg.wasm.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Music',
    color: 'blue',
    related: ['convertir-video', 'comprimir-video', 'convertir-audio'],
  },
  {
    slug: 'video-a-gif',
    name: 'Vídeo a GIF',
    description: 'Convierte un fragmento de vídeo en un GIF animado.',
    longDescription: 'Transforma un clip de vídeo en un GIF animado ajustando el punto de inicio, la duración, los fotogramas por segundo y el ancho. Ideal para crear previews y contenido para redes sociales.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Clapperboard',
    color: 'blue',
    related: ['recortar-video', 'convertir-video', 'comprimir-video'],
  },
  {
    slug: 'recortar-video',
    name: 'Recortar vídeo',
    description: 'Recorta un vídeo seleccionando el punto de inicio y fin.',
    longDescription: 'Elimina partes del principio o el final de tu vídeo con precisión de segundos. Define el punto de entrada y salida y descarga el fragmento seleccionado. Sin pérdida de calidad cuando se usa copia directa.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Scissors',
    color: 'blue',
    related: ['comprimir-video', 'convertir-video', 'video-a-gif'],
  },

  // ── AUDIO · BÁSICAS ──────────────────────────────────────────
  {
    slug: 'comprimir-audio',
    name: 'Comprimir audio',
    description: 'Reduce el tamaño de archivos de audio ajustando el bitrate.',
    longDescription: 'Comprime archivos MP3, WAV y OGG reduciendo el bitrate. Elige entre varias calidades según tu necesidad: desde 64 kbps para voz hasta 320 kbps para música. Procesamiento 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Headphones',
    color: 'blue',
    related: ['convertir-audio', 'cortar-audio', 'extraer-audio'],
  },
  {
    slug: 'convertir-audio',
    name: 'Convertir audio',
    description: 'Convierte entre MP3, WAV, OGG y AAC sin pérdida innecesaria.',
    longDescription: 'Cambia el formato de tus archivos de audio entre MP3, WAV, OGG y AAC en el navegador con FFmpeg.wasm. Ideal para compatibilidad con distintos reproductores y plataformas.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Music2',
    color: 'blue',
    related: ['comprimir-audio', 'cortar-audio', 'extraer-audio'],
  },
  {
    slug: 'cortar-audio',
    name: 'Cortar audio',
    description: 'Recorta un fragmento de audio por tiempo de inicio y fin.',
    longDescription: 'Extrae un fragmento de cualquier archivo de audio definiendo el segundo de inicio y el segundo de fin. Útil para crear clips, tonos de llamada o extractos de canciones.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Radio',
    color: 'blue',
    related: ['comprimir-audio', 'unir-audios', 'convertir-audio'],
  },
  {
    slug: 'unir-audios',
    name: 'Unir audios',
    description: 'Combina varios archivos de audio en uno solo manteniendo el orden.',
    longDescription: 'Fusiona múltiples archivos de audio en un único archivo. Reordena las pistas antes de unirlas. El resultado se descarga como MP3. Sin enviar archivos al servidor.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'ListMusic',
    color: 'blue',
    related: ['cortar-audio', 'comprimir-audio', 'convertir-audio'],
  },
  {
    slug: 'cambiar-volumen',
    name: 'Cambiar volumen',
    description: 'Sube o baja el volumen de un audio con precisión en dB.',
    longDescription: 'Ajusta el volumen de cualquier archivo de audio entre -20 dB y +20 dB. También puedes normalizar el audio al nivel máximo sin distorsión. Procesamiento 100% local con FFmpeg.wasm.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Volume2',
    color: 'blue',
    related: ['comprimir-audio', 'cortar-audio', 'convertir-audio'],
  },

  // ── DEVELOPER · BÁSICAS ───────────────────────────────────────
  {
    slug: 'svg-a-png',
    name: 'SVG a PNG',
    description: 'Convierte SVG vectorial a PNG rasterizado con el tamaño que quieras.',
    longDescription: 'Renderiza cualquier SVG a PNG con dimensiones y fondo personalizados. Perfecto para exportar iconos, logos e ilustraciones vectoriales a formatos compatibles con cualquier plataforma.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'FileCode2',
    color: 'blue',
    related: ['imagen-a-base64', 'generar-favicon', 'eliminar-exif'],
  },
  {
    slug: 'colores-imagen',
    name: 'Colores de imagen',
    description: 'Extrae hex, RGB y HSL de los colores dominantes.',
    longDescription: 'Analiza tu imagen y obtén los colores dominantes con sus valores en hex, RGB y HSL listos para copiar. Ideal para documentar paletas de marca o extraer colores de referencias visuales.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Pipette',
    color: 'blue',
    related: ['eliminar-exif', 'imagen-a-base64', 'svg-a-png'],
  },
  {
    slug: 'eliminar-exif',
    name: 'Eliminar EXIF',
    description: 'Borra metadatos EXIF (GPS, cámara, fecha) de tus imágenes.',
    longDescription: 'Elimina todos los metadatos EXIF de tus fotos antes de publicarlas. Incluye GPS, modelo de cámara, fecha y hora. El proceso usa Canvas API y nunca sale de tu navegador.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'ShieldOff',
    color: 'blue',
    related: ['comprimir', 'colores-imagen', 'imagen-a-base64'],
  },
  {
    slug: 'imagen-a-base64',
    name: 'Imagen a Base64',
    description: 'Codifica cualquier imagen en Base64 para incrustarla en código.',
    longDescription: 'Convierte tu imagen a una cadena Base64 lista para usar en HTML, CSS, JSON o JavaScript. Elimina peticiones HTTP adicionales para imágenes pequeñas. Muestra ejemplos de uso en cada contexto.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Hash',
    color: 'blue',
    related: ['svg-a-png', 'generar-favicon', 'eliminar-exif'],
  },
  {
    slug: 'generar-favicon',
    name: 'Generar favicon',
    description: 'Genera todos los tamaños de favicon desde una imagen.',
    longDescription: 'Crea los tamaños estándar de favicon (16×16, 32×32, 48×48 y 180×180) desde cualquier imagen. Descarga cada PNG con el nombre correcto y copia las etiquetas HTML listas para tu `<head>`.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Bookmark',
    color: 'blue',
    related: ['svg-a-png', 'imagen-a-base64', 'recorte-circular'],
  },

  // ── IMAGEN · NUEVAS ─────────────────────────────────────────
  {
    slug: 'espejo',
    name: 'Voltear imagen',
    description: 'Refleja tu imagen horizontal o verticalmente con un clic.',
    longDescription: 'Voltea cualquier imagen en espejo de forma horizontal, vertical o en ambos ejes. Preview instantáneo y descarga en el mismo formato que el original.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'FlipHorizontal2',
    color: 'blue',
    related: ['girar', 'recortar', 'editor'],
  },
  {
    slug: 'foto-carnet',
    name: 'Foto carnet',
    description: 'Crea fotos de carnet y pasaporte con los tamaños oficiales.',
    longDescription: 'Genera fotos de carnet para DNI, pasaporte, visado, carnet de conducir y más. Selecciona el formato estándar y recorta automáticamente tu foto al tamaño oficial.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'IdCard',
    color: 'blue',
    related: ['recortar', 'redimensionar', 'recorte-circular'],
  },
  {
    slug: 'redimensionar-redes',
    name: 'Redimensionar para redes',
    description: 'Ajusta tus imágenes a los tamaños perfectos para Instagram, YouTube y más.',
    longDescription: 'Redimensiona tus imágenes a las medidas exactas de Instagram, Twitter/X, YouTube, Facebook, TikTok, LinkedIn y WhatsApp con un solo clic. Elige entre recortar o rellenar con fondo.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'MonitorSmartphone',
    color: 'blue',
    related: ['redimensionar', 'recortar', 'thumbnail-youtube'],
  },
  {
    slug: 'efecto-vintage',
    name: 'Efecto vintage',
    description: 'Aplica efectos retro y vintage a tus fotos: sepia, cine, polaroid y más.',
    longDescription: 'Transforma tus fotos con efectos vintage profesionales. Elige entre Sepia, Vintage (faded + viñeta), Cine (grano + alto contraste), Polaroid y Noir. Controla la intensidad con un slider.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Sparkles',
    color: 'purple',
    related: ['blancoynegro', 'editor', 'invertir'],
  },
  {
    slug: 'thumbnail-youtube',
    name: 'Miniatura YouTube',
    description: 'Crea miniaturas de YouTube de 1280×720 con texto y fondo personalizado.',
    longDescription: 'Diseña miniaturas profesionales para YouTube en el tamaño perfecto (1280×720 px). Sube una imagen de fondo, añade título con fuente y color personalizables, y descarga en PNG.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'PlaySquare',
    color: 'purple',
    related: ['redimensionar-redes', 'texto', 'editor'],
  },
  {
    slug: 'imagenes-a-gif',
    name: 'Imágenes a GIF',
    description: 'Convierte varias imágenes en un GIF animado con velocidad ajustable.',
    longDescription: 'Crea GIFs animados desde múltiples imágenes JPG o PNG. Sube hasta 20 fotogramas, ajusta la velocidad de cada frame y el ancho del GIF. Optimización de paleta con FFmpeg.wasm.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'ImagePlay',
    color: 'purple',
    related: ['video-a-gif', 'collage', 'comprimir'],
  },

  // ── PDF · NUEVAS ─────────────────────────────────────────────
  {
    slug: 'marca-agua-pdf',
    name: 'Marca de agua en PDF',
    description: 'Añade texto en marca de agua a todas las páginas de un PDF.',
    longDescription: 'Protege tus documentos PDF añadiendo un texto en marca de agua diagonal. Controla el texto, tamaño, opacidad y color. Se aplica a todas las páginas. Sin subir archivos al servidor.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Stamp',
    color: 'blue',
    related: ['proteger-pdf', 'numerar-paginas-pdf', 'firmar-pdf'],
  },
  {
    slug: 'numerar-paginas-pdf',
    name: 'Numerar páginas PDF',
    description: 'Añade numeración automática a todas las páginas de tu PDF.',
    longDescription: 'Numera las páginas de tu PDF automáticamente. Elige la posición (inferior centro, inferior derecho, superior derecho), el número inicial y el formato (1, Página 1/N). Sin instalar nada.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'ListOrdered',
    color: 'blue',
    related: ['marca-agua-pdf', 'rotar-pdf', 'comprimir-pdf'],
  },
  {
    slug: 'firmar-pdf',
    name: 'Firmar PDF',
    description: 'Dibuja tu firma y colócala en cualquier página del PDF.',
    longDescription: 'Crea tu firma digital dibujándola con el ratón o el dedo, y colócala en la página que quieras del PDF. Elige el tamaño y la posición exacta. Procesamiento 100% local.',
    category: 'Avanzadas',
    domain: 'pdf',
    icon: 'PenLine',
    color: 'orange',
    related: ['proteger-pdf', 'marca-agua-pdf', 'unir-pdfs'],
  },
  {
    slug: 'pdf-a-png',
    name: 'PDF a PNG',
    description: 'Convierte cada página de tu PDF en una imagen PNG sin pérdida.',
    longDescription: 'Renderiza cada página de un PDF como imagen PNG de alta calidad. PNG es ideal para PDFs con texto, gráficos vectoriales o cuando necesitas fondo transparente.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'ScanLine',
    color: 'blue',
    related: ['pdf-a-jpg', 'dividir-pdf', 'comprimir-pdf'],
  },
  {
    slug: 'reordenar-paginas-pdf',
    name: 'Reordenar páginas PDF',
    description: 'Cambia el orden de las páginas de tu PDF arrastrando o con botones.',
    longDescription: 'Reorganiza las páginas de cualquier PDF de forma visual. Mueve las páginas hacia arriba o hacia abajo con botones intuitivos y descarga el PDF con el nuevo orden.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'ArrowUpDown',
    color: 'blue',
    related: ['dividir-pdf', 'unir-pdfs', 'extraer-paginas-pdf'],
  },
  {
    slug: 'recortar-pdf',
    name: 'Recortar márgenes PDF',
    description: 'Elimina los márgenes en blanco de un PDF ajustando el área visible.',
    longDescription: 'Recorta los márgenes de todas las páginas de un PDF definiendo el margen en milímetros para cada lado. Ideal para eliminar espacios en blanco excesivos de documentos escaneados.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Maximize2',
    color: 'blue',
    related: ['comprimir-pdf', 'rotar-pdf', 'extraer-paginas-pdf'],
  },

  // ── DEVELOPER · NUEVAS ───────────────────────────────────────
  {
    slug: 'generar-qr',
    name: 'Generador de QR',
    description: 'Crea códigos QR para URLs, texto o contactos en segundos.',
    longDescription: 'Genera códigos QR personalizados para cualquier URL, texto o dato. Ajusta el tamaño, los colores y el nivel de corrección de errores. Descarga en PNG sin registro.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'QrCode',
    color: 'blue',
    related: ['imagen-a-base64', 'generar-favicon', 'svg-a-png'],
  },
  {
    slug: 'formatear-json',
    name: 'Formatear JSON',
    description: 'Formatea, valida y minifica JSON con un clic.',
    longDescription: 'Pega tu JSON y fórmatealo con 2 o 4 espacios, minifícalo o valídalo al instante. Muestra errores con el número de línea. Copia el resultado o descárgalo como .json.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Braces',
    color: 'blue',
    related: ['codificar-url', 'imagen-a-base64', 'convertir-color'],
  },
  {
    slug: 'codificar-url',
    name: 'Codificar URL',
    description: 'Codifica y decodifica URLs y componentes de URL al instante.',
    longDescription: 'Codifica y decodifica URLs usando encodeURI / decodeURI y encodeURIComponent / decodeURIComponent. Resultado en tiempo real al escribir. Copia con un clic.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Link2',
    color: 'blue',
    related: ['formatear-json', 'imagen-a-base64', 'convertir-color'],
  },
  {
    slug: 'convertir-color',
    name: 'Convertir colores',
    description: 'Convierte colores entre HEX, RGB, HSL y HSB al instante.',
    longDescription: 'Introduce un color en cualquier formato (HEX, RGB, HSL, HSB) y obtén automáticamente sus equivalentes en todos los demás. Previsualiza el color y copia cada valor con un clic.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Paintbrush2',
    color: 'blue',
    related: ['colores-imagen', 'paleta', 'codificar-url'],
  },

  // ── VIDEO · NUEVAS ───────────────────────────────────────────
  {
    slug: 'cambiar-velocidad',
    name: 'Cambiar velocidad de vídeo',
    description: 'Acelera o ralentiza tu vídeo manteniendo la calidad de audio.',
    longDescription: 'Cambia la velocidad de reproducción de cualquier vídeo: desde 0.25x en cámara lenta hasta 2x en acelerado. El audio se ajusta automáticamente con corrección de tono. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Gauge',
    color: 'blue',
    related: ['comprimir-video', 'recortar-video', 'convertir-video'],
  },
  {
    slug: 'anadir-audio-video',
    name: 'Añadir audio a vídeo',
    description: 'Reemplaza o mezcla el audio de un vídeo con otro archivo de audio.',
    longDescription: 'Combina un vídeo con un archivo de audio. Elige entre reemplazar el audio existente o mezclarlo como música de fondo. El vídeo no se re-codifica, manteniendo la calidad original.',
    category: 'Básicas',
    domain: 'video',
    icon: 'AudioLines',
    color: 'blue',
    related: ['extraer-audio', 'convertir-video', 'comprimir-video'],
  },

  // ── AUDIO · NUEVAS ───────────────────────────────────────────
  {
    slug: 'velocidad-audio',
    name: 'Cambiar velocidad de audio',
    description: 'Acelera o ralentiza el audio conservando el tono original.',
    longDescription: 'Ajusta la velocidad de reproducción de cualquier audio entre 0.5x y 2x sin cambiar el tono (pitch preservation). Perfecto para podcasts, audiolibros o prácticas musicales.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'FastForward',
    color: 'blue',
    related: ['cortar-audio', 'cambiar-volumen', 'convertir-audio'],
  },
  {
    slug: 'revertir-audio',
    name: 'Revertir audio',
    description: 'Reproduce tu audio al revés con el efecto reverse.',
    longDescription: 'Invierte un archivo de audio para reproducirlo de atrás hacia adelante. Perfecto para efectos creativos, música experimental y producción de audio. Procesamiento 100% local con FFmpeg.wasm.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Rewind',
    color: 'blue',
    related: ['cortar-audio', 'convertir-audio', 'comprimir-audio'],
  },

  // ── VÍDEO · NUEVAS 2 ─────────────────────────────────────────
  {
    slug: 'rotar-video',
    name: 'Rotar vídeo',
    description: 'Gira tu vídeo 90°, 180° o 270° con un clic.',
    longDescription: 'Rota cualquier vídeo grabado en orientación incorrecta. Elige entre 90° a la derecha, 90° a la izquierda o 180°. El audio se preserva. Procesamiento 100% local con FFmpeg.wasm.',
    category: 'Básicas',
    domain: 'video',
    icon: 'RotateCw',
    color: 'blue',
    related: ['comprimir-video', 'recortar-video', 'convertir-video'],
  },
  {
    slug: 'unir-videos',
    name: 'Unir vídeos',
    description: 'Combina varios vídeos en uno solo manteniendo el orden.',
    longDescription: 'Fusiona múltiples vídeos en un único archivo MP4. Sube hasta 10 clips, reordénalos y descarga el resultado. Re-codificación con libx264 para máxima compatibilidad.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Merge',
    color: 'blue',
    related: ['recortar-video', 'comprimir-video', 'convertir-video'],
  },
  {
    slug: 'silenciar-video',
    name: 'Silenciar vídeo',
    description: 'Elimina el audio de un vídeo con un solo clic.',
    longDescription: 'Elimina completamente la pista de audio de cualquier vídeo. El stream de vídeo se copia sin re-codificar para preservar la calidad original. Perfecto para vídeos de fondo o presentaciones.',
    category: 'Básicas',
    domain: 'video',
    icon: 'VolumeX',
    color: 'blue',
    related: ['anadir-audio-video', 'comprimir-video', 'recortar-video'],
  },
  {
    slug: 'capturar-fotograma',
    name: 'Capturar fotograma',
    description: 'Extrae cualquier fotograma de un vídeo como imagen PNG.',
    longDescription: 'Selecciona el segundo exacto de tu vídeo y extrae ese fotograma como imagen PNG de alta calidad. Ideal para crear miniaturas, capturas de pantalla o extraer imágenes de grabaciones.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Camera',
    color: 'blue',
    related: ['video-a-gif', 'recortar-video', 'comprimir-video'],
  },

  // ── DEVELOPER · NUEVAS 2 ─────────────────────────────────────
  {
    slug: 'base64-texto',
    name: 'Base64 texto',
    description: 'Codifica y decodifica texto en Base64 al instante.',
    longDescription: 'Convierte cualquier texto a Base64 y viceversa de forma instantánea. Soporta Unicode, emojis y caracteres especiales. Útil para tokens de API, configuraciones, credenciales y datos en JSON.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Binary',
    color: 'blue',
    related: ['imagen-a-base64', 'codificar-url', 'formatear-json'],
  },
  {
    slug: 'minificador-css',
    name: 'Minificador CSS',
    description: 'Minifica y comprime tu CSS eliminando espacios y comentarios.',
    longDescription: 'Reduce el tamaño de tus archivos CSS eliminando espacios en blanco, saltos de línea y comentarios. También incluye un modo de formateo para hacer legible un CSS minificado. Sin dependencias externas.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Code2',
    color: 'blue',
    related: ['formatear-json', 'codificar-url', 'convertir-color'],
  },
  {
    slug: 'csv-a-json',
    name: 'CSV a JSON',
    description: 'Convierte archivos CSV a JSON y viceversa en segundos.',
    longDescription: 'Transforma datos CSV a formato JSON estructurado usando la primera fila como cabecera. También convierte JSON a CSV. Perfecto para importar/exportar datos entre herramientas y APIs.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Table',
    color: 'blue',
    related: ['formatear-json', 'codificar-url', 'base64-texto'],
  },
  {
    slug: 'calcular-hash',
    name: 'Calcular hash',
    description: 'Genera hashes SHA-256, SHA-1 y SHA-512 de texto o archivos.',
    longDescription: 'Calcula el hash criptográfico de texto o archivos usando SHA-1, SHA-256, SHA-384 y SHA-512 con la Web Crypto API nativa del navegador. Útil para verificar integridad de archivos y seguridad.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'ShieldCheck',
    color: 'blue',
    related: ['base64-texto', 'imagen-a-base64', 'codificar-url'],
  },

  // ── IMAGEN · NUEVAS 3 ─────────────────────────────────────────
  {
    slug: 'ajustar-hsb',
    name: 'Ajustar color',
    description: 'Ajusta el tono, saturación, brillo y contraste con sliders en tiempo real.',
    longDescription: 'Modifica el tono (hue), la saturación, el brillo y el contraste de tu imagen con sliders precisos. Preview en tiempo real y exportación en JPG. Ideal para corrección de color sin software.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'SlidersHorizontal',
    color: 'purple',
    related: ['editor', 'blancoynegro', 'efecto-vintage'],
  },
  {
    slug: 'efecto-boceto',
    name: 'Efecto boceto',
    description: 'Convierte cualquier foto en un dibujo a lápiz con efecto pencil sketch.',
    longDescription: 'Transforma tus fotografías en bocetos artísticos a lápiz usando la técnica color dodge. Controla la suavidad del trazo con un slider. El resultado es una imagen en escala de grises con aspecto de dibujo manual.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Pencil',
    color: 'purple',
    related: ['blancoynegro', 'efecto-vintage', 'editor'],
  },
  {
    slug: 'cambiar-fondo',
    name: 'Cambiar fondo',
    description: 'Reemplaza el fondo de tu imagen por cualquier color sólido.',
    longDescription: 'Añade o cambia el color de fondo de cualquier imagen. Especialmente útil para PNGs con transparencia: rellena el fondo con blanco, negro o cualquier color personalizado. Ideal para e-commerce y redes sociales.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'PaintBucket',
    color: 'blue',
    related: ['eliminar-fondo', 'recorte-circular', 'marco'],
  },
  {
    slug: 'mosaico',
    name: 'Mosaico de imagen',
    description: 'Repite tu imagen en una cuadrícula de N×M tiles.',
    longDescription: 'Crea un mosaico repitiendo tu imagen en una cuadrícula configurable de hasta 6 columnas × 6 filas. Perfecto para fondos de pantalla, papeles de pared, packaging y efectos de diseño gráfico.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Grid2X2',
    color: 'purple',
    related: ['collage', 'redimensionar', 'marco'],
  },
  {
    slug: 'efecto-duotono',
    name: 'Efecto duotono',
    description: 'Aplica un efecto duotono de dos colores a tus imágenes.',
    longDescription: 'Crea efectos duotono profesionales mapeando las sombras y las luces de tu imagen a dos colores personalizados. Incluye 5 combinaciones preset populares y soporte para cualquier color.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Layers2',
    color: 'purple',
    related: ['blancoynegro', 'editor', 'efecto-vintage'],
  },

  // ── PDF · NUEVAS 3 ────────────────────────────────────────────
  {
    slug: 'eliminar-paginas-pdf',
    name: 'Eliminar páginas PDF',
    description: 'Borra páginas específicas de un PDF por número o rango.',
    longDescription: 'Elimina páginas individuales o rangos de páginas de cualquier PDF. Indica qué páginas borrar (ej: 1, 3, 5-7) y descarga el PDF resultante sin esas páginas. Sin límite de tamaño, 100% local.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FileX',
    color: 'blue',
    related: ['extraer-paginas-pdf', 'dividir-pdf', 'reordenar-paginas-pdf'],
  },
  {
    slug: 'anadir-imagen-pdf',
    name: 'Añadir imagen a PDF',
    description: 'Inserta una imagen JPG o PNG en una página de tu PDF.',
    longDescription: 'Añade imágenes (JPG o PNG) en cualquier página de tu PDF con control de posición X/Y y tamaño. Perfecto para insertar firmas escaneadas, sellos, logos o cualquier imagen en un documento.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'ImagePlus',
    color: 'blue',
    related: ['firmar-pdf', 'anadir-texto-pdf', 'marca-agua-pdf'],
  },
  {
    slug: 'pdf-en-blanco',
    name: 'Crear PDF en blanco',
    description: 'Genera un PDF en blanco con el tamaño y número de páginas que necesites.',
    longDescription: 'Crea PDFs en blanco con tamaños estándar (A4, A3, A5, Carta, Legal) en orientación vertical u horizontal. Elige cuántas páginas necesitas (hasta 100). Ideal para plantillas, formularios y documentos base.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'FilePlus',
    color: 'blue',
    related: ['unir-pdfs', 'anadir-texto-pdf', 'anadir-imagen-pdf'],
  },

  // ── VÍDEO · NUEVAS 3 ─────────────────────────────────────────
  {
    slug: 'voltear-video',
    name: 'Voltear vídeo',
    description: 'Voltea tu vídeo en espejo horizontal, vertical o en ambos ejes.',
    longDescription: 'Refleja cualquier vídeo horizontal o verticalmente con FFmpeg.wasm. Útil para corregir vídeos de cámara frontal, crear efectos de espejo o cumplir requisitos de plataformas. El audio se preserva.',
    category: 'Básicas',
    domain: 'video',
    icon: 'FlipHorizontal',
    color: 'blue',
    related: ['rotar-video', 'comprimir-video', 'recortar-video'],
  },
  {
    slug: 'recortar-area-video',
    name: 'Recortar área de vídeo',
    description: 'Recorta un área específica del vídeo definiendo ancho, alto y posición.',
    longDescription: 'Extrae un área rectangular de cualquier vídeo especificando el ancho, alto y las coordenadas de inicio en píxeles. Ideal para eliminar barras negras, recortar bordes o extraer una región de interés. El audio se preserva.',
    category: 'Básicas',
    domain: 'video',
    icon: 'ScanSearch',
    color: 'blue',
    related: ['recortar-video', 'cambiar-resolucion-video', 'comprimir-video'],
  },
  {
    slug: 'cambiar-resolucion-video',
    name: 'Cambiar resolución de vídeo',
    description: 'Escala tu vídeo a 4K, 1080p, 720p, 480p o una resolución personalizada.',
    longDescription: 'Cambia la resolución de cualquier vídeo con presets populares o dimensiones personalizadas. La herramienta mantiene la relación de aspecto original y añade padding si es necesario. El audio se preserva.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Monitor',
    color: 'blue',
    related: ['comprimir-video', 'convertir-video', 'recortar-area-video'],
  },
  {
    slug: 'marca-agua-video',
    name: 'Marca de agua en vídeo',
    description: 'Añade texto como marca de agua a tu vídeo con posición y opacidad ajustables.',
    longDescription: 'Incrusta texto permanente como marca de agua en tu vídeo usando FFmpeg drawtext. Elige la posición (centro, esquinas), el tamaño de fuente y la opacidad. El texto queda grabado en el stream de vídeo.',
    category: 'Básicas',
    domain: 'video',
    icon: 'Stamp',
    color: 'blue',
    related: ['silenciar-video', 'comprimir-video', 'recortar-video'],
  },

  // ── AUDIO · NUEVAS 2 ─────────────────────────────────────────
  {
    slug: 'agregar-fade-audio',
    name: 'Agregar fade a audio',
    description: 'Añade fade in y fade out suaves a cualquier archivo de audio.',
    longDescription: 'Aplica efectos de entrada y salida gradual a tu audio. Configura la duración del fade in (inicio desde silencio) y fade out (fin en silencio) de forma independiente. Compatible con todos los formatos de audio.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'TrendingUp',
    color: 'blue',
    related: ['cortar-audio', 'cambiar-volumen', 'mezclar-audios'],
  },
  {
    slug: 'mezclar-audios',
    name: 'Mezclar audios',
    description: 'Combina dos pistas de audio en una sola con control de volumen independiente.',
    longDescription: 'Superpone dos archivos de audio en una sola pista. Controla el volumen de cada pista de forma independiente. Perfecto para añadir música de fondo a una locución, crear karaoke o superponer efectos de sonido.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Combine',
    color: 'blue',
    related: ['unir-audios', 'cambiar-volumen', 'agregar-fade-audio'],
  },
  {
    slug: 'cambiar-tono',
    name: 'Cambiar tono de audio',
    description: 'Sube o baja el tono musical de un audio en semitonos sin cambiar la velocidad.',
    longDescription: 'Ajusta el tono de cualquier audio entre -12 y +12 semitonos (una octava completa) sin modificar la velocidad de reproducción. Ideal para transportar música, crear efectos de voz o adaptar canciones para cantar.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Music4',
    color: 'blue',
    related: ['velocidad-audio', 'convertir-audio', 'comprimir-audio'],
  },

  // ── DEVELOPER · NUEVAS 3 ─────────────────────────────────────
  {
    slug: 'regex-tester',
    name: 'Tester de Regex',
    description: 'Prueba expresiones regulares JavaScript con resaltado de coincidencias en tiempo real.',
    longDescription: 'Escribe una expresión regular y pruébala contra cualquier texto. Las coincidencias se resaltan en tiempo real, con detalle de índices y grupos de captura. Soporta todos los flags de JavaScript (g, i, m, s).',
    category: 'Básicas',
    domain: 'developer',
    icon: 'TestTube2',
    color: 'blue',
    related: ['formatear-json', 'contador-palabras', 'codificar-url'],
  },
  {
    slug: 'generador-uuid',
    name: 'Generador de UUID',
    description: 'Genera UUIDs v4 criptográficamente seguros al instante.',
    longDescription: 'Genera uno o hasta 100 UUID versión 4 usando la Web Crypto API. Opciones para formato con/sin guiones y en mayúsculas o minúsculas. Copia cada UUID o todos de una vez al portapapeles.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Fingerprint',
    color: 'blue',
    related: ['calcular-hash', 'base64-texto', 'codificar-url'],
  },
  {
    slug: 'contador-palabras',
    name: 'Contador de palabras',
    description: 'Cuenta palabras, caracteres, frases, párrafos y tiempo de lectura al instante.',
    longDescription: 'Analiza cualquier texto y muestra en tiempo real el número de palabras, caracteres (con y sin espacios), frases, párrafos, líneas y tiempo estimado de lectura. Útil para artículos, SEO, tweets y documentos académicos.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'AlignLeft',
    color: 'blue',
    related: ['regex-tester', 'formatear-json', 'minificador-html'],
  },
  {
    slug: 'convertir-timestamp',
    name: 'Convertir timestamp',
    description: 'Convierte entre Unix timestamp y fecha legible en ambas direcciones.',
    longDescription: 'Transforma Unix timestamps (segundos o milisegundos) a fechas legibles en formato local, UTC e ISO 8601, y viceversa. Detecta automáticamente si el timestamp está en segundos o milisegundos. Copia cualquier resultado.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Clock',
    color: 'blue',
    related: ['formatear-json', 'generador-uuid', 'codificar-url'],
  },
  {
    slug: 'minificador-html',
    name: 'Minificador HTML',
    description: 'Minifica y formatea HTML eliminando espacios y comentarios innecesarios.',
    longDescription: 'Reduce el tamaño de archivos HTML eliminando comentarios, espacios en blanco redundantes y saltos de línea. También incluye modo de formateo para hacer legible un HTML comprimido. Sin dependencias externas.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'FileCode',
    color: 'blue',
    related: ['minificador-css', 'formatear-json', 'contador-palabras'],
  },

  // ── IMAGEN · NUEVAS 2 ─────────────────────────────────────────
  {
    slug: 'imagen-a-webp',
    name: 'Convertir a WebP',
    description: 'Convierte imágenes JPG y PNG a formato WebP con calidad ajustable.',
    longDescription: 'Transforma tus imágenes JPG o PNG al formato WebP de Google, que ofrece hasta un 30% menos de tamaño con la misma calidad visual. Elige la calidad y descarga al instante. 100% en el navegador.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'ImageUp',
    color: 'blue',
    related: ['comprimir', 'convertir', 'redimensionar'],
  },

  // ── PDF · NUEVAS 2 ────────────────────────────────────────────
  {
    slug: 'anadir-texto-pdf',
    name: 'Añadir texto a PDF',
    description: 'Inserta texto personalizado en cualquier posición de tu PDF.',
    longDescription: 'Añade anotaciones de texto a cualquier página de un PDF. Personaliza la posición (X/Y en porcentaje), el tamaño de fuente y el color. Perfecto para completar formularios o añadir notas. 100% local.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Type',
    color: 'blue',
    related: ['firmar-pdf', 'marca-agua-pdf', 'numerar-paginas-pdf'],
  },

  // ── DEVELOPER · NUEVAS ───────────────────────────────────────
  {
    slug: 'generador-contrasenas',
    name: 'Generador de contraseñas',
    description: 'Genera contraseñas seguras y aleatorias con opciones avanzadas.',
    longDescription: 'Crea contraseñas criptográficamente seguras usando la Web Crypto API. Controla la longitud (6-64 caracteres), los tipos de caracteres y genera hasta 20 contraseñas a la vez. Indicador de fortaleza incluido.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'KeyRound',
    color: 'blue',
    related: ['calcular-hash', 'generador-uuid', 'base64-texto'],
  },
  {
    slug: 'conversor-unidades',
    name: 'Conversor de unidades',
    description: 'Convierte entre unidades de longitud, masa, temperatura, velocidad y más.',
    longDescription: 'Conversor de unidades con 8 categorías: Longitud, Masa, Temperatura, Área, Velocidad, Volumen, Datos y Tiempo. Conversión instantánea al escribir, con botón de intercambio rápido. Sin dependencias externas.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'ArrowLeftRight',
    color: 'blue',
    related: ['convertir-timestamp', 'formatear-json', 'codificar-url'],
  },
  {
    slug: 'lorem-ipsum',
    name: 'Lorem ipsum',
    description: 'Genera párrafos, frases o palabras de texto Lorem Ipsum.',
    longDescription: 'Genera texto de relleno Lorem ipsum en tres modos: párrafos, frases o palabras sueltas. Ajusta la cantidad con un slider, activa o desactiva el inicio clásico «Lorem ipsum…», y descarga el resultado como .txt.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'AlignJustify',
    color: 'blue',
    related: ['contador-palabras', 'minificador-html', 'formatear-json'],
  },
  {
    slug: 'gradiente-css',
    name: 'Generador de gradientes CSS',
    description: 'Crea gradientes CSS lineales y radiales con preview en tiempo real.',
    longDescription: 'Diseña gradientes CSS con hasta 5 colores, control de ángulo y posición de cada stop. Elige entre gradiente lineal o radial. Preview en tiempo real y copia el código CSS listo para usar. Incluye 5 presets.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Layers',
    color: 'blue',
    related: ['convertir-color', 'colores-imagen', 'minificador-css'],
  },
  {
    slug: 'minificador-js',
    name: 'Minificador JavaScript',
    description: 'Minifica y formatea código JavaScript eliminando comentarios y espacios.',
    longDescription: 'Reduce el tamaño de archivos JavaScript eliminando comentarios de bloque y de línea, y colapsando espacios en blanco. También incluye modo de formateo para hacer legible un JS minificado. Muestra el porcentaje de reducción.',
    category: 'Básicas',
    domain: 'developer',
    icon: 'Zap',
    color: 'blue',
    related: ['minificador-css', 'minificador-html', 'formatear-json'],
  },

  // ── AUDIO · NUEVAS ───────────────────────────────────────────
  {
    slug: 'anadir-silencio',
    name: 'Añadir silencio a audio',
    description: 'Añade segundos de silencio al inicio y/o al final de cualquier audio.',
    longDescription: 'Agrega silencio al comienzo o al final de un archivo de audio con precisión de 0.5 segundos. Útil para dar margen antes de que empiece una pista, sincronizar audios o cumplir requisitos de duración. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Volume',
    color: 'blue',
    related: ['cortar-audio', 'unir-audios', 'agregar-fade-audio'],
  },
  {
    slug: 'convertir-a-mono',
    name: 'Convertir estéreo a mono',
    description: 'Mezcla los canales estéreo en uno solo para reducir el tamaño del audio.',
    longDescription: 'Convierte cualquier audio estéreo a mono mezclando los canales izquierdo y derecho. El resultado ocupa aproximadamente la mitad de espacio. Ideal para podcasts, voz en off y archivos donde el tamaño importa. FFmpeg.wasm, 100% local.',
    category: 'Básicas',
    domain: 'audio',
    icon: 'Headphones',
    color: 'blue',
    related: ['comprimir-audio', 'convertir-audio', 'cambiar-volumen'],
  },

  // ── IMAGEN · NUEVAS ──────────────────────────────────────────
  {
    slug: 'comprimir-objetivo',
    name: 'Comprimir a tamaño objetivo',
    description: 'Comprime tu imagen hasta alcanzar un tamaño de archivo específico en KB.',
    longDescription: 'Introduce el peso máximo deseado (en KB) y la herramienta busca automáticamente el nivel de calidad JPEG que produce el archivo más grande posible sin superar ese límite. Búsqueda binaria con hasta 15 iteraciones. 100% en el navegador.',
    category: 'Básicas',
    domain: 'imagen',
    icon: 'Target',
    color: 'blue',
    related: ['comprimir', 'redimensionar', 'convertir'],
  },
  {
    slug: 'fondo-degradado',
    name: 'Fondo degradado',
    description: 'Añade un fondo con degradado de color a tu imagen o PNG transparente.',
    longDescription: 'Aplica un fondo de gradiente lineal o radial a cualquier imagen. Especialmente útil para PNGs con transparencia: logos, ilustraciones o imágenes con fondo eliminado. Elige entre 5 presets o personaliza los colores. Exporta como PNG.',
    category: 'Creativas',
    domain: 'imagen',
    icon: 'Sunset',
    color: 'purple',
    related: ['cambiar-fondo', 'eliminar-fondo', 'marco'],
  },

  // ── PDF · NUEVAS ─────────────────────────────────────────────
  {
    slug: 'metadatos-pdf',
    name: 'Metadatos de PDF',
    description: 'Visualiza y edita el título, autor, asunto y palabras clave de un PDF.',
    longDescription: 'Lee y modifica los metadatos de cualquier PDF: título, autor, asunto y palabras clave. También muestra el creador del documento y la fecha de creación. Guarda el PDF modificado con los nuevos metadatos. 100% local con pdf-lib.',
    category: 'Básicas',
    domain: 'pdf',
    icon: 'Info',
    color: 'blue',
    related: ['proteger-pdf', 'eliminar-password-pdf', 'comprimir-pdf'],
  },
];

export const TOOL_BY_SLUG: Record<string, ToolMeta> = Object.fromEntries(
  TOOLS.map((t) => [t.slug, t]),
);

export const ACCEPTED_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/gif'];
export const MAX_FILE_SIZE = 50 * 1024 * 1024; // 50 MB
